// Code generated by ent, DO NOT EDIT.

package unblockrequest

import (
	"entgo.io/ent/dialect/sql"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContainsFold(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldValue, v))
}

// TargetHostname applies equality check predicate on the "target_hostname" field. It's identical to TargetHostnameEQ.
func TargetHostname(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldTargetHostname, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContainsFold(FieldType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldHasSuffix(FieldValue, v))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContainsFold(FieldValue, v))
}

// TargetHostnameEQ applies the EQ predicate on the "target_hostname" field.
func TargetHostnameEQ(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldTargetHostname, v))
}

// TargetHostnameNEQ applies the NEQ predicate on the "target_hostname" field.
func TargetHostnameNEQ(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNEQ(FieldTargetHostname, v))
}

// TargetHostnameIn applies the In predicate on the "target_hostname" field.
func TargetHostnameIn(vs ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldIn(FieldTargetHostname, vs...))
}

// TargetHostnameNotIn applies the NotIn predicate on the "target_hostname" field.
func TargetHostnameNotIn(vs ...string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNotIn(FieldTargetHostname, vs...))
}

// TargetHostnameGT applies the GT predicate on the "target_hostname" field.
func TargetHostnameGT(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGT(FieldTargetHostname, v))
}

// TargetHostnameGTE applies the GTE predicate on the "target_hostname" field.
func TargetHostnameGTE(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGTE(FieldTargetHostname, v))
}

// TargetHostnameLT applies the LT predicate on the "target_hostname" field.
func TargetHostnameLT(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLT(FieldTargetHostname, v))
}

// TargetHostnameLTE applies the LTE predicate on the "target_hostname" field.
func TargetHostnameLTE(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLTE(FieldTargetHostname, v))
}

// TargetHostnameContains applies the Contains predicate on the "target_hostname" field.
func TargetHostnameContains(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContains(FieldTargetHostname, v))
}

// TargetHostnameHasPrefix applies the HasPrefix predicate on the "target_hostname" field.
func TargetHostnameHasPrefix(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldHasPrefix(FieldTargetHostname, v))
}

// TargetHostnameHasSuffix applies the HasSuffix predicate on the "target_hostname" field.
func TargetHostnameHasSuffix(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldHasSuffix(FieldTargetHostname, v))
}

// TargetHostnameEqualFold applies the EqualFold predicate on the "target_hostname" field.
func TargetHostnameEqualFold(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEqualFold(FieldTargetHostname, v))
}

// TargetHostnameContainsFold applies the ContainsFold predicate on the "target_hostname" field.
func TargetHostnameContainsFold(v string) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldContainsFold(FieldTargetHostname, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UnblockRequest) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UnblockRequest) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UnblockRequest) predicate.UnblockRequest {
	return predicate.UnblockRequest(sql.NotPredicates(p))
}
