// Code generated by ent, DO NOT EDIT.

package instance

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the instance type in the database.
	Label = "instance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHostname holds the string denoting the hostname field in the database.
	FieldHostname = "hostname"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldPolicyOverride holds the string denoting the policy_override field in the database.
	FieldPolicyOverride = "policy_override"
	// FieldFilterMode holds the string denoting the filter_mode field in the database.
	FieldFilterMode = "filter_mode"
	// FieldReportedVersion holds the string denoting the reported_version field in the database.
	FieldReportedVersion = "reported_version"
	// FieldReportedHash holds the string denoting the reported_hash field in the database.
	FieldReportedHash = "reported_hash"
	// FieldLastSeenAt holds the string denoting the last_seen_at field in the database.
	FieldLastSeenAt = "last_seen_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// Table holds the table name of the instance in the database.
	Table = "fleet_instances"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "fleet_instances"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "fleet_groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for instance fields.
var Columns = []string{
	FieldID,
	FieldHostname,
	FieldGroupID,
	FieldPolicyOverride,
	FieldFilterMode,
	FieldReportedVersion,
	FieldReportedHash,
	FieldLastSeenAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultFilterMode holds the default value on creation for the "filter_mode" field.
	DefaultFilterMode string
	// DefaultReportedVersion holds the default value on creation for the "reported_version" field.
	DefaultReportedVersion string
	// DefaultReportedHash holds the default value on creation for the "reported_hash" field.
	DefaultReportedHash string
)

// OrderOption defines the ordering options for the Instance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHostname orders the results by the hostname field.
func ByHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHostname, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByPolicyOverride orders the results by the policy_override field.
func ByPolicyOverride(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyOverride, opts...).ToFunc()
}

// ByFilterMode orders the results by the filter_mode field.
func ByFilterMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilterMode, opts...).ToFunc()
}

// ByReportedVersion orders the results by the reported_version field.
func ByReportedVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedVersion, opts...).ToFunc()
}

// ByReportedHash orders the results by the reported_hash field.
func ByReportedHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedHash, opts...).ToFunc()
}

// ByLastSeenAt orders the results by the last_seen_at field.
func ByLastSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSeenAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
