// Code generated by ent, DO NOT EDIT.

package instance

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldID, id))
}

// Hostname applies equality check predicate on the "hostname" field. It's identical to HostnameEQ.
func Hostname(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldHostname, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldGroupID, v))
}

// PolicyOverride applies equality check predicate on the "policy_override" field. It's identical to PolicyOverrideEQ.
func PolicyOverride(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldPolicyOverride, v))
}

// FilterMode applies equality check predicate on the "filter_mode" field. It's identical to FilterModeEQ.
func FilterMode(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldFilterMode, v))
}

// ReportedVersion applies equality check predicate on the "reported_version" field. It's identical to ReportedVersionEQ.
func ReportedVersion(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldReportedVersion, v))
}

// ReportedHash applies equality check predicate on the "reported_hash" field. It's identical to ReportedHashEQ.
func ReportedHash(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldReportedHash, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldLastSeenAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldCreatedAt, v))
}

// HostnameEQ applies the EQ predicate on the "hostname" field.
func HostnameEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldHostname, v))
}

// HostnameNEQ applies the NEQ predicate on the "hostname" field.
func HostnameNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldHostname, v))
}

// HostnameIn applies the In predicate on the "hostname" field.
func HostnameIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldHostname, vs...))
}

// HostnameNotIn applies the NotIn predicate on the "hostname" field.
func HostnameNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldHostname, vs...))
}

// HostnameGT applies the GT predicate on the "hostname" field.
func HostnameGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldHostname, v))
}

// HostnameGTE applies the GTE predicate on the "hostname" field.
func HostnameGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldHostname, v))
}

// HostnameLT applies the LT predicate on the "hostname" field.
func HostnameLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldHostname, v))
}

// HostnameLTE applies the LTE predicate on the "hostname" field.
func HostnameLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldHostname, v))
}

// HostnameContains applies the Contains predicate on the "hostname" field.
func HostnameContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldHostname, v))
}

// HostnameHasPrefix applies the HasPrefix predicate on the "hostname" field.
func HostnameHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldHostname, v))
}

// HostnameHasSuffix applies the HasSuffix predicate on the "hostname" field.
func HostnameHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldHostname, v))
}

// HostnameEqualFold applies the EqualFold predicate on the "hostname" field.
func HostnameEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldHostname, v))
}

// HostnameContainsFold applies the ContainsFold predicate on the "hostname" field.
func HostnameContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldHostname, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldGroupID))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldGroupID, v))
}

// PolicyOverrideEQ applies the EQ predicate on the "policy_override" field.
func PolicyOverrideEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldPolicyOverride, v))
}

// PolicyOverrideNEQ applies the NEQ predicate on the "policy_override" field.
func PolicyOverrideNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldPolicyOverride, v))
}

// PolicyOverrideIn applies the In predicate on the "policy_override" field.
func PolicyOverrideIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldPolicyOverride, vs...))
}

// PolicyOverrideNotIn applies the NotIn predicate on the "policy_override" field.
func PolicyOverrideNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldPolicyOverride, vs...))
}

// PolicyOverrideGT applies the GT predicate on the "policy_override" field.
func PolicyOverrideGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldPolicyOverride, v))
}

// PolicyOverrideGTE applies the GTE predicate on the "policy_override" field.
func PolicyOverrideGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldPolicyOverride, v))
}

// PolicyOverrideLT applies the LT predicate on the "policy_override" field.
func PolicyOverrideLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldPolicyOverride, v))
}

// PolicyOverrideLTE applies the LTE predicate on the "policy_override" field.
func PolicyOverrideLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldPolicyOverride, v))
}

// PolicyOverrideContains applies the Contains predicate on the "policy_override" field.
func PolicyOverrideContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldPolicyOverride, v))
}

// PolicyOverrideHasPrefix applies the HasPrefix predicate on the "policy_override" field.
func PolicyOverrideHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldPolicyOverride, v))
}

// PolicyOverrideHasSuffix applies the HasSuffix predicate on the "policy_override" field.
func PolicyOverrideHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldPolicyOverride, v))
}

// PolicyOverrideIsNil applies the IsNil predicate on the "policy_override" field.
func PolicyOverrideIsNil() predicate.Instance {
	return predicate.Instance(sql.FieldIsNull(FieldPolicyOverride))
}

// PolicyOverrideNotNil applies the NotNil predicate on the "policy_override" field.
func PolicyOverrideNotNil() predicate.Instance {
	return predicate.Instance(sql.FieldNotNull(FieldPolicyOverride))
}

// PolicyOverrideEqualFold applies the EqualFold predicate on the "policy_override" field.
func PolicyOverrideEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldPolicyOverride, v))
}

// PolicyOverrideContainsFold applies the ContainsFold predicate on the "policy_override" field.
func PolicyOverrideContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldPolicyOverride, v))
}

// FilterModeEQ applies the EQ predicate on the "filter_mode" field.
func FilterModeEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldFilterMode, v))
}

// FilterModeNEQ applies the NEQ predicate on the "filter_mode" field.
func FilterModeNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldFilterMode, v))
}

// FilterModeIn applies the In predicate on the "filter_mode" field.
func FilterModeIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldFilterMode, vs...))
}

// FilterModeNotIn applies the NotIn predicate on the "filter_mode" field.
func FilterModeNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldFilterMode, vs...))
}

// FilterModeGT applies the GT predicate on the "filter_mode" field.
func FilterModeGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldFilterMode, v))
}

// FilterModeGTE applies the GTE predicate on the "filter_mode" field.
func FilterModeGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldFilterMode, v))
}

// FilterModeLT applies the LT predicate on the "filter_mode" field.
func FilterModeLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldFilterMode, v))
}

// FilterModeLTE applies the LTE predicate on the "filter_mode" field.
func FilterModeLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldFilterMode, v))
}

// FilterModeContains applies the Contains predicate on the "filter_mode" field.
func FilterModeContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldFilterMode, v))
}

// FilterModeHasPrefix applies the HasPrefix predicate on the "filter_mode" field.
func FilterModeHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldFilterMode, v))
}

// FilterModeHasSuffix applies the HasSuffix predicate on the "filter_mode" field.
func FilterModeHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldFilterMode, v))
}

// FilterModeEqualFold applies the EqualFold predicate on the "filter_mode" field.
func FilterModeEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldFilterMode, v))
}

// FilterModeContainsFold applies the ContainsFold predicate on the "filter_mode" field.
func FilterModeContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldFilterMode, v))
}

// ReportedVersionEQ applies the EQ predicate on the "reported_version" field.
func ReportedVersionEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldReportedVersion, v))
}

// ReportedVersionNEQ applies the NEQ predicate on the "reported_version" field.
func ReportedVersionNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldReportedVersion, v))
}

// ReportedVersionIn applies the In predicate on the "reported_version" field.
func ReportedVersionIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldReportedVersion, vs...))
}

// ReportedVersionNotIn applies the NotIn predicate on the "reported_version" field.
func ReportedVersionNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldReportedVersion, vs...))
}

// ReportedVersionGT applies the GT predicate on the "reported_version" field.
func ReportedVersionGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldReportedVersion, v))
}

// ReportedVersionGTE applies the GTE predicate on the "reported_version" field.
func ReportedVersionGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldReportedVersion, v))
}

// ReportedVersionLT applies the LT predicate on the "reported_version" field.
func ReportedVersionLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldReportedVersion, v))
}

// ReportedVersionLTE applies the LTE predicate on the "reported_version" field.
func ReportedVersionLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldReportedVersion, v))
}

// ReportedVersionContains applies the Contains predicate on the "reported_version" field.
func ReportedVersionContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldReportedVersion, v))
}

// ReportedVersionHasPrefix applies the HasPrefix predicate on the "reported_version" field.
func ReportedVersionHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldReportedVersion, v))
}

// ReportedVersionHasSuffix applies the HasSuffix predicate on the "reported_version" field.
func ReportedVersionHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldReportedVersion, v))
}

// ReportedVersionEqualFold applies the EqualFold predicate on the "reported_version" field.
func ReportedVersionEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldReportedVersion, v))
}

// ReportedVersionContainsFold applies the ContainsFold predicate on the "reported_version" field.
func ReportedVersionContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldReportedVersion, v))
}

// ReportedHashEQ applies the EQ predicate on the "reported_hash" field.
func ReportedHashEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldReportedHash, v))
}

// ReportedHashNEQ applies the NEQ predicate on the "reported_hash" field.
func ReportedHashNEQ(v string) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldReportedHash, v))
}

// ReportedHashIn applies the In predicate on the "reported_hash" field.
func ReportedHashIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldReportedHash, vs...))
}

// ReportedHashNotIn applies the NotIn predicate on the "reported_hash" field.
func ReportedHashNotIn(vs ...string) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldReportedHash, vs...))
}

// ReportedHashGT applies the GT predicate on the "reported_hash" field.
func ReportedHashGT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldReportedHash, v))
}

// ReportedHashGTE applies the GTE predicate on the "reported_hash" field.
func ReportedHashGTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldReportedHash, v))
}

// ReportedHashLT applies the LT predicate on the "reported_hash" field.
func ReportedHashLT(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldReportedHash, v))
}

// ReportedHashLTE applies the LTE predicate on the "reported_hash" field.
func ReportedHashLTE(v string) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldReportedHash, v))
}

// ReportedHashContains applies the Contains predicate on the "reported_hash" field.
func ReportedHashContains(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContains(FieldReportedHash, v))
}

// ReportedHashHasPrefix applies the HasPrefix predicate on the "reported_hash" field.
func ReportedHashHasPrefix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasPrefix(FieldReportedHash, v))
}

// ReportedHashHasSuffix applies the HasSuffix predicate on the "reported_hash" field.
func ReportedHashHasSuffix(v string) predicate.Instance {
	return predicate.Instance(sql.FieldHasSuffix(FieldReportedHash, v))
}

// ReportedHashEqualFold applies the EqualFold predicate on the "reported_hash" field.
func ReportedHashEqualFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldEqualFold(FieldReportedHash, v))
}

// ReportedHashContainsFold applies the ContainsFold predicate on the "reported_hash" field.
func ReportedHashContainsFold(v string) predicate.Instance {
	return predicate.Instance(sql.FieldContainsFold(FieldReportedHash, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...int64) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...int64) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldLastSeenAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Instance {
	return predicate.Instance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Instance {
	return predicate.Instance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Instance {
	return predicate.Instance(sql.FieldLTE(FieldCreatedAt, v))
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.Instance {
	return predicate.Instance(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Instance) predicate.Instance {
	return predicate.Instance(sql.NotPredicates(p))
}
