---
coverage:
  status:
    project:
      default:
        target: '55%'
        threshold: null
    patch: false
    changes: false

ignore:
  - 'dashboard/store/ent'  # generated ent client + schema/migrate scaffolding
