# FOSSA configuration for g0efilter
version: 3

# Project settings
project:
  name: g0efilter
  team: g0lab
  url: https://github.com/g0lab/g0efilter

# License policy configuration
policies:
  # Allow CC-BY-SA-3.0 for Unicode data only
  allow:
    - license: "CC-BY-SA-3.0"
      reason: "Unicode/CLDR data tables - factual data, not copyrightable code"
      packages:
        - "golang.org/x/text"

# Custom license classifications
custom-license-mapping:
  "golang.org/x/text":
    description: "Primary BSD-3-Clause with Unicode data tables under CC-BY-SA-3.0"
    category: "permissive-with-data"
    notes: "CC-BY-SA components are factual Unicode data compilations"

# Analysis configuration
analyze:
  modules:
    - path: "."
      type: "go"