version: 2

project_name: g0efilter

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: g0efilter
    main: ./cmd/g0efilter
    binary: g0efilter
    env: ["CGO_ENABLED=0"]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

  - id: g0efilter-dashboard
    main: ./cmd/g0efilter-dashboard
    binary: g0efilter-dashboard
    env: ["CGO_ENABLED=0"]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .Commit }}
      - -X main.date={{ .Date }}

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - id: g0efilter
    dockerfile: ./Dockerfile
    images:
      - docker.io/g0lab/g0efilter
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64

  - id: g0efilter-dashboard
    dockerfile: ./Dockerfile-dashboard
    images:
      - docker.io/g0lab/g0efilter-dashboard
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64

release:
  github:
    owner: g0lab
    name: g0efilter
  draft: false          
  prerelease: auto

changelog:
  use: github 
  format: "{{ .Message }} (by {{ with .AuthorUsername }}{{ . }}{{ else }}{{ .AuthorName }}{{ end }})"
  abbrev: -1                 
  sort: asc
  groups:                     
    - title: "Enhancements"
      regexp: '^.*?(?i:(feat|feature|enhance|add|introduce|allow|improve|bump|migrate|implement|support|enable|update|refactor))'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?(?i:(fix|bug|revert|hotfix|correct|workaround|issue))'
      order: 1
    - title: "Documentation"
      regexp: '^.*?(?i:(docs?|documentation|readme))'
      order: 2
    - title: "Misc"
      order: 99
  filters:
    exclude:
      - '^ci:'
      - '^tests:'
      - '^docs:'
      - '^style:'
      - '^test:'
      - '^doc:'
      - '^chore:'
      - 'merge conflict'
      - 'Merge branch'
      - 'Merge pull request'

signs:
- cmd: cosign
  signature: "${artifact}.sig"
  certificate: "${artifact}.pem"
  args:
    - "sign-blob"
    - "--oidc-issuer=https://token.actions.githubusercontent.com"
    - "--output-certificate=${certificate}"
    - "--output-signature=${signature}"
    - "${artifact}"
    - "--yes"
  artifacts: all
  output: true

docker_signs:
- cmd: cosign
  artifacts: manifests
  output: true
  args:
  - 'sign'
  - '${artifact}'
  - '--yes'