FROM gcr.io/distroless/static:nonroot

USER nonroot
WORKDIR /app/data
WORKDIR /app

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/g0efilter-dashboard /app/g0efilter-dashboard

EXPOSE 8081

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD ["/app/g0efilter-dashboard", "healthcheck"]

ENTRYPOINT ["/app/g0efilter-dashboard"]
