// Code generated by ent, DO NOT EDIT.

package group

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// FilterMode applies equality check predicate on the "filter_mode" field. It's identical to FilterModeEQ.
func FilterMode(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldFilterMode, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldName, v))
}

// PolicyEQ applies the EQ predicate on the "policy" field.
func PolicyEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldPolicy, v))
}

// PolicyNEQ applies the NEQ predicate on the "policy" field.
func PolicyNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldPolicy, v))
}

// PolicyIn applies the In predicate on the "policy" field.
func PolicyIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldPolicy, vs...))
}

// PolicyNotIn applies the NotIn predicate on the "policy" field.
func PolicyNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldPolicy, vs...))
}

// PolicyGT applies the GT predicate on the "policy" field.
func PolicyGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldPolicy, v))
}

// PolicyGTE applies the GTE predicate on the "policy" field.
func PolicyGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldPolicy, v))
}

// PolicyLT applies the LT predicate on the "policy" field.
func PolicyLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldPolicy, v))
}

// PolicyLTE applies the LTE predicate on the "policy" field.
func PolicyLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldPolicy, v))
}

// PolicyContains applies the Contains predicate on the "policy" field.
func PolicyContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldPolicy, v))
}

// PolicyHasPrefix applies the HasPrefix predicate on the "policy" field.
func PolicyHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldPolicy, v))
}

// PolicyHasSuffix applies the HasSuffix predicate on the "policy" field.
func PolicyHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldPolicy, v))
}

// PolicyEqualFold applies the EqualFold predicate on the "policy" field.
func PolicyEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldPolicy, v))
}

// PolicyContainsFold applies the ContainsFold predicate on the "policy" field.
func PolicyContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldPolicy, v))
}

// FilterModeEQ applies the EQ predicate on the "filter_mode" field.
func FilterModeEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldFilterMode, v))
}

// FilterModeNEQ applies the NEQ predicate on the "filter_mode" field.
func FilterModeNEQ(v string) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldFilterMode, v))
}

// FilterModeIn applies the In predicate on the "filter_mode" field.
func FilterModeIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldFilterMode, vs...))
}

// FilterModeNotIn applies the NotIn predicate on the "filter_mode" field.
func FilterModeNotIn(vs ...string) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldFilterMode, vs...))
}

// FilterModeGT applies the GT predicate on the "filter_mode" field.
func FilterModeGT(v string) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldFilterMode, v))
}

// FilterModeGTE applies the GTE predicate on the "filter_mode" field.
func FilterModeGTE(v string) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldFilterMode, v))
}

// FilterModeLT applies the LT predicate on the "filter_mode" field.
func FilterModeLT(v string) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldFilterMode, v))
}

// FilterModeLTE applies the LTE predicate on the "filter_mode" field.
func FilterModeLTE(v string) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldFilterMode, v))
}

// FilterModeContains applies the Contains predicate on the "filter_mode" field.
func FilterModeContains(v string) predicate.Group {
	return predicate.Group(sql.FieldContains(FieldFilterMode, v))
}

// FilterModeHasPrefix applies the HasPrefix predicate on the "filter_mode" field.
func FilterModeHasPrefix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasPrefix(FieldFilterMode, v))
}

// FilterModeHasSuffix applies the HasSuffix predicate on the "filter_mode" field.
func FilterModeHasSuffix(v string) predicate.Group {
	return predicate.Group(sql.FieldHasSuffix(FieldFilterMode, v))
}

// FilterModeEqualFold applies the EqualFold predicate on the "filter_mode" field.
func FilterModeEqualFold(v string) predicate.Group {
	return predicate.Group(sql.FieldEqualFold(FieldFilterMode, v))
}

// FilterModeContainsFold applies the ContainsFold predicate on the "filter_mode" field.
func FilterModeContainsFold(v string) predicate.Group {
	return predicate.Group(sql.FieldContainsFold(FieldFilterMode, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Group {
	return predicate.Group(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Group {
	return predicate.Group(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Group {
	return predicate.Group(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Group {
	return predicate.Group(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Group {
	return predicate.Group(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasInstances applies the HasEdge predicate on the "instances" edge.
func HasInstances() predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InstancesTable, InstancesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInstancesWith applies the HasEdge predicate on the "instances" edge with a given conditions (other predicates).
func HasInstancesWith(preds ...predicate.Instance) predicate.Group {
	return predicate.Group(func(s *sql.Selector) {
		step := newInstancesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Group) predicate.Group {
	return predicate.Group(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Group) predicate.Group {
	return predicate.Group(sql.NotPredicates(p))
}
