// Code generated by ent, DO NOT EDIT.

package completedunblock

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the completedunblock type in the database.
	Label = "completed_unblock"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldTargetHostname holds the string denoting the target_hostname field in the database.
	FieldTargetHostname = "target_hostname"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the completedunblock in the database.
	Table = "completed_unblocks"
)

// Columns holds all SQL columns for completedunblock fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldValue,
	FieldTargetHostname,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTargetHostname holds the default value on creation for the "target_hostname" field.
	DefaultTargetHostname string
)

// OrderOption defines the ordering options for the CompletedUnblock queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByTargetHostname orders the results by the target_hostname field.
func ByTargetHostname(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetHostname, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
