---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: g0efilter-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resourceNames:
  - g0efilter-sidecar-injector
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - update
- apiGroups:
  - g0efilter.g0lab.com
  resources:
  - clusteregresspolicies
  - egresspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - g0efilter.g0lab.com
  resources:
  - egresspolicies/status
  verbs:
  - get
  - patch
  - update
