// Code generated by ent, DO NOT EDIT.

package logevent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the logevent type in the database.
	Label = "log_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTs holds the string denoting the ts field in the database.
	FieldTs = "ts"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// FieldSearch holds the string denoting the search field in the database.
	FieldSearch = "search"
	// Table holds the table name of the logevent in the database.
	Table = "logs"
)

// Columns holds all SQL columns for logevent fields.
var Columns = []string{
	FieldID,
	FieldTs,
	FieldData,
	FieldSearch,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the LogEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTs orders the results by the ts field.
func ByTs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTs, opts...).ToFunc()
}

// ByData orders the results by the data field.
func ByData(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldData, opts...).ToFunc()
}

// BySearch orders the results by the search field.
func BySearch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSearch, opts...).ToFunc()
}
