// Code generated by ent, DO NOT EDIT.

package logevent

import (
	"entgo.io/ent/dialect/sql"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLTE(FieldID, id))
}

// Ts applies equality check predicate on the "ts" field. It's identical to TsEQ.
func Ts(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldTs, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldData, v))
}

// Search applies equality check predicate on the "search" field. It's identical to SearchEQ.
func Search(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldSearch, v))
}

// TsEQ applies the EQ predicate on the "ts" field.
func TsEQ(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldTs, v))
}

// TsNEQ applies the NEQ predicate on the "ts" field.
func TsNEQ(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNEQ(FieldTs, v))
}

// TsIn applies the In predicate on the "ts" field.
func TsIn(vs ...int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldIn(FieldTs, vs...))
}

// TsNotIn applies the NotIn predicate on the "ts" field.
func TsNotIn(vs ...int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNotIn(FieldTs, vs...))
}

// TsGT applies the GT predicate on the "ts" field.
func TsGT(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGT(FieldTs, v))
}

// TsGTE applies the GTE predicate on the "ts" field.
func TsGTE(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGTE(FieldTs, v))
}

// TsLT applies the LT predicate on the "ts" field.
func TsLT(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLT(FieldTs, v))
}

// TsLTE applies the LTE predicate on the "ts" field.
func TsLTE(v int64) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLTE(FieldTs, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLTE(FieldData, v))
}

// DataContains applies the Contains predicate on the "data" field.
func DataContains(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldContains(FieldData, v))
}

// DataHasPrefix applies the HasPrefix predicate on the "data" field.
func DataHasPrefix(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldHasPrefix(FieldData, v))
}

// DataHasSuffix applies the HasSuffix predicate on the "data" field.
func DataHasSuffix(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldHasSuffix(FieldData, v))
}

// DataEqualFold applies the EqualFold predicate on the "data" field.
func DataEqualFold(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEqualFold(FieldData, v))
}

// DataContainsFold applies the ContainsFold predicate on the "data" field.
func DataContainsFold(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldContainsFold(FieldData, v))
}

// SearchEQ applies the EQ predicate on the "search" field.
func SearchEQ(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEQ(FieldSearch, v))
}

// SearchNEQ applies the NEQ predicate on the "search" field.
func SearchNEQ(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNEQ(FieldSearch, v))
}

// SearchIn applies the In predicate on the "search" field.
func SearchIn(vs ...string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldIn(FieldSearch, vs...))
}

// SearchNotIn applies the NotIn predicate on the "search" field.
func SearchNotIn(vs ...string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldNotIn(FieldSearch, vs...))
}

// SearchGT applies the GT predicate on the "search" field.
func SearchGT(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGT(FieldSearch, v))
}

// SearchGTE applies the GTE predicate on the "search" field.
func SearchGTE(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldGTE(FieldSearch, v))
}

// SearchLT applies the LT predicate on the "search" field.
func SearchLT(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLT(FieldSearch, v))
}

// SearchLTE applies the LTE predicate on the "search" field.
func SearchLTE(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldLTE(FieldSearch, v))
}

// SearchContains applies the Contains predicate on the "search" field.
func SearchContains(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldContains(FieldSearch, v))
}

// SearchHasPrefix applies the HasPrefix predicate on the "search" field.
func SearchHasPrefix(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldHasPrefix(FieldSearch, v))
}

// SearchHasSuffix applies the HasSuffix predicate on the "search" field.
func SearchHasSuffix(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldHasSuffix(FieldSearch, v))
}

// SearchEqualFold applies the EqualFold predicate on the "search" field.
func SearchEqualFold(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldEqualFold(FieldSearch, v))
}

// SearchContainsFold applies the ContainsFold predicate on the "search" field.
func SearchContainsFold(v string) predicate.LogEvent {
	return predicate.LogEvent(sql.FieldContainsFold(FieldSearch, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LogEvent) predicate.LogEvent {
	return predicate.LogEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LogEvent) predicate.LogEvent {
	return predicate.LogEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LogEvent) predicate.LogEvent {
	return predicate.LogEvent(sql.NotPredicates(p))
}
