// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// CompletedUnblock is the predicate function for completedunblock builders.
type CompletedUnblock func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Instance is the predicate function for instance builders.
type Instance func(*sql.Selector)

// LogEvent is the predicate function for logevent builders.
type LogEvent func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// UnblockRequest is the predicate function for unblockrequest builders.
type UnblockRequest func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
