// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/apikey"
)

// APIKeyCreate is the builder for creating a APIKey entity.
type APIKeyCreate struct {
	config
	mutation *APIKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLabel sets the "label" field.
func (_c *APIKeyCreate) SetLabel(v string) *APIKeyCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *APIKeyCreate) SetKeyHash(v []byte) *APIKeyCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *APIKeyCreate) SetKeyPrefix(v string) *APIKeyCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyCreate) SetCreatedAt(v int64) *APIKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *APIKeyCreate) SetLastUsedAt(v int64) *APIKeyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *APIKeyCreate) SetNillableLastUsedAt(v *int64) *APIKeyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *APIKeyCreate) SetRevokedAt(v int64) *APIKeyCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *APIKeyCreate) SetNillableRevokedAt(v *int64) *APIKeyCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *APIKeyCreate) SetID(v string) *APIKeyCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the APIKeyMutation object of the builder.
func (_c *APIKeyCreate) Mutation() *APIKeyMutation {
	return _c.mutation
}

// Save creates the APIKey in the database.
func (_c *APIKeyCreate) Save(ctx context.Context) (*APIKey, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyCreate) SaveX(ctx context.Context) *APIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyCreate) check() error {
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "APIKey.label"`)}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "APIKey.key_hash"`)}
	}
	if _, ok := _c.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "APIKey.key_prefix"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKey.created_at"`)}
	}
	return nil
}

func (_c *APIKeyCreate) sqlSave(ctx context.Context) (*APIKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected APIKey.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyCreate) createSpec() (*APIKey, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikey.Table, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(apikey.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeBytes, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikey.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeInt64, value)
		_node.LastUsedAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeInt64, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKey.Create().
//		SetLabel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyUpsert) {
//			SetLabel(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyUpsertOne {
	_c.conflict = opts
	return &APIKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyCreate) OnConflictColumns(columns ...string) *APIKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyUpsertOne is the builder for "upsert"-ing
	//  one APIKey node.
	APIKeyUpsertOne struct {
		create *APIKeyCreate
	}

	// APIKeyUpsert is the "OnConflict" setter.
	APIKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetLabel sets the "label" field.
func (u *APIKeyUpsert) SetLabel(v string) *APIKeyUpsert {
	u.Set(apikey.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *APIKeyUpsert) UpdateLabel() *APIKeyUpsert {
	u.SetExcluded(apikey.FieldLabel)
	return u
}

// SetKeyHash sets the "key_hash" field.
func (u *APIKeyUpsert) SetKeyHash(v []byte) *APIKeyUpsert {
	u.Set(apikey.FieldKeyHash, v)
	return u
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *APIKeyUpsert) UpdateKeyHash() *APIKeyUpsert {
	u.SetExcluded(apikey.FieldKeyHash)
	return u
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *APIKeyUpsert) SetKeyPrefix(v string) *APIKeyUpsert {
	u.Set(apikey.FieldKeyPrefix, v)
	return u
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *APIKeyUpsert) UpdateKeyPrefix() *APIKeyUpsert {
	u.SetExcluded(apikey.FieldKeyPrefix)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *APIKeyUpsert) SetCreatedAt(v int64) *APIKeyUpsert {
	u.Set(apikey.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *APIKeyUpsert) UpdateCreatedAt() *APIKeyUpsert {
	u.SetExcluded(apikey.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *APIKeyUpsert) AddCreatedAt(v int64) *APIKeyUpsert {
	u.Add(apikey.FieldCreatedAt, v)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *APIKeyUpsert) SetLastUsedAt(v int64) *APIKeyUpsert {
	u.Set(apikey.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *APIKeyUpsert) UpdateLastUsedAt() *APIKeyUpsert {
	u.SetExcluded(apikey.FieldLastUsedAt)
	return u
}

// AddLastUsedAt adds v to the "last_used_at" field.
func (u *APIKeyUpsert) AddLastUsedAt(v int64) *APIKeyUpsert {
	u.Add(apikey.FieldLastUsedAt, v)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *APIKeyUpsert) ClearLastUsedAt() *APIKeyUpsert {
	u.SetNull(apikey.FieldLastUsedAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *APIKeyUpsert) SetRevokedAt(v int64) *APIKeyUpsert {
	u.Set(apikey.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *APIKeyUpsert) UpdateRevokedAt() *APIKeyUpsert {
	u.SetExcluded(apikey.FieldRevokedAt)
	return u
}

// AddRevokedAt adds v to the "revoked_at" field.
func (u *APIKeyUpsert) AddRevokedAt(v int64) *APIKeyUpsert {
	u.Add(apikey.FieldRevokedAt, v)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *APIKeyUpsert) ClearRevokedAt() *APIKeyUpsert {
	u.SetNull(apikey.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.APIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(apikey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *APIKeyUpsertOne) UpdateNewValues() *APIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(apikey.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyUpsertOne) Ignore() *APIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyUpsertOne) DoNothing() *APIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyCreate.OnConflict
// documentation for more info.
func (u *APIKeyUpsertOne) Update(set func(*APIKeyUpsert)) *APIKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetLabel sets the "label" field.
func (u *APIKeyUpsertOne) SetLabel(v string) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *APIKeyUpsertOne) UpdateLabel() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateLabel()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *APIKeyUpsertOne) SetKeyHash(v []byte) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *APIKeyUpsertOne) UpdateKeyHash() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateKeyHash()
	})
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *APIKeyUpsertOne) SetKeyPrefix(v string) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetKeyPrefix(v)
	})
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *APIKeyUpsertOne) UpdateKeyPrefix() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateKeyPrefix()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *APIKeyUpsertOne) SetCreatedAt(v int64) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *APIKeyUpsertOne) AddCreatedAt(v int64) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *APIKeyUpsertOne) UpdateCreatedAt() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *APIKeyUpsertOne) SetLastUsedAt(v int64) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// AddLastUsedAt adds v to the "last_used_at" field.
func (u *APIKeyUpsertOne) AddLastUsedAt(v int64) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.AddLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *APIKeyUpsertOne) UpdateLastUsedAt() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *APIKeyUpsertOne) ClearLastUsedAt() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *APIKeyUpsertOne) SetRevokedAt(v int64) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetRevokedAt(v)
	})
}

// AddRevokedAt adds v to the "revoked_at" field.
func (u *APIKeyUpsertOne) AddRevokedAt(v int64) *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.AddRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *APIKeyUpsertOne) UpdateRevokedAt() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *APIKeyUpsertOne) ClearRevokedAt() *APIKeyUpsertOne {
	return u.Update(func(s *APIKeyUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *APIKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: APIKeyUpsertOne.ID is not supported by MySQL driver. Use APIKeyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyCreateBulk is the builder for creating many APIKey entities in bulk.
type APIKeyCreateBulk struct {
	config
	err      error
	builders []*APIKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKey entities in the database.
func (_c *APIKeyCreateBulk) Save(ctx context.Context) ([]*APIKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyCreateBulk) SaveX(ctx context.Context) []*APIKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyUpsert) {
//			SetLabel(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyUpsertBulk {
	_c.conflict = opts
	return &APIKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyCreateBulk) OnConflictColumns(columns ...string) *APIKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyUpsertBulk{
		create: _c,
	}
}

// APIKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKey nodes.
type APIKeyUpsertBulk struct {
	create *APIKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(apikey.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *APIKeyUpsertBulk) UpdateNewValues() *APIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(apikey.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyUpsertBulk) Ignore() *APIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyUpsertBulk) DoNothing() *APIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyUpsertBulk) Update(set func(*APIKeyUpsert)) *APIKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetLabel sets the "label" field.
func (u *APIKeyUpsertBulk) SetLabel(v string) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *APIKeyUpsertBulk) UpdateLabel() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateLabel()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *APIKeyUpsertBulk) SetKeyHash(v []byte) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *APIKeyUpsertBulk) UpdateKeyHash() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateKeyHash()
	})
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *APIKeyUpsertBulk) SetKeyPrefix(v string) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetKeyPrefix(v)
	})
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *APIKeyUpsertBulk) UpdateKeyPrefix() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateKeyPrefix()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *APIKeyUpsertBulk) SetCreatedAt(v int64) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *APIKeyUpsertBulk) AddCreatedAt(v int64) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *APIKeyUpsertBulk) UpdateCreatedAt() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *APIKeyUpsertBulk) SetLastUsedAt(v int64) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// AddLastUsedAt adds v to the "last_used_at" field.
func (u *APIKeyUpsertBulk) AddLastUsedAt(v int64) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.AddLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *APIKeyUpsertBulk) UpdateLastUsedAt() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *APIKeyUpsertBulk) ClearLastUsedAt() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *APIKeyUpsertBulk) SetRevokedAt(v int64) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.SetRevokedAt(v)
	})
}

// AddRevokedAt adds v to the "revoked_at" field.
func (u *APIKeyUpsertBulk) AddRevokedAt(v int64) *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.AddRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *APIKeyUpsertBulk) UpdateRevokedAt() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *APIKeyUpsertBulk) ClearRevokedAt() *APIKeyUpsertBulk {
	return u.Update(func(s *APIKeyUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *APIKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
