// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/completedunblock"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// CompletedUnblockDelete is the builder for deleting a CompletedUnblock entity.
type CompletedUnblockDelete struct {
	config
	hooks    []Hook
	mutation *CompletedUnblockMutation
}

// Where appends a list predicates to the CompletedUnblockDelete builder.
func (_d *CompletedUnblockDelete) Where(ps ...predicate.CompletedUnblock) *CompletedUnblockDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CompletedUnblockDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompletedUnblockDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CompletedUnblockDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(completedunblock.Table, sqlgraph.NewFieldSpec(completedunblock.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CompletedUnblockDeleteOne is the builder for deleting a single CompletedUnblock entity.
type CompletedUnblockDeleteOne struct {
	_d *CompletedUnblockDelete
}

// Where appends a list predicates to the CompletedUnblockDelete builder.
func (_d *CompletedUnblockDeleteOne) Where(ps ...predicate.CompletedUnblock) *CompletedUnblockDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CompletedUnblockDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{completedunblock.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompletedUnblockDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
