// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/g0lab/g0efilter/dashboard/store/ent/completedunblock"
)

// CompletedUnblock is the model entity for the CompletedUnblock schema.
type CompletedUnblock struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// TargetHostname holds the value of the "target_hostname" field.
	TargetHostname string `json:"target_hostname,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt  int64 `json:"completed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompletedUnblock) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case completedunblock.FieldID, completedunblock.FieldCompletedAt:
			values[i] = new(sql.NullInt64)
		case completedunblock.FieldType, completedunblock.FieldValue, completedunblock.FieldTargetHostname:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompletedUnblock fields.
func (_m *CompletedUnblock) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case completedunblock.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case completedunblock.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case completedunblock.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case completedunblock.FieldTargetHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_hostname", values[i])
			} else if value.Valid {
				_m.TargetHostname = value.String
			}
		case completedunblock.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the CompletedUnblock.
// This includes values selected through modifiers, order, etc.
func (_m *CompletedUnblock) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CompletedUnblock.
// Note that you need to call CompletedUnblock.Unwrap() before calling this method if this CompletedUnblock
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompletedUnblock) Update() *CompletedUnblockUpdateOne {
	return NewCompletedUnblockClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompletedUnblock entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompletedUnblock) Unwrap() *CompletedUnblock {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompletedUnblock is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompletedUnblock) String() string {
	var builder strings.Builder
	builder.WriteString("CompletedUnblock(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("target_hostname=")
	builder.WriteString(_m.TargetHostname)
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedAt))
	builder.WriteByte(')')
	return builder.String()
}

// CompletedUnblocks is a parsable slice of CompletedUnblock.
type CompletedUnblocks []*CompletedUnblock
