// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/completedunblock"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// CompletedUnblockUpdate is the builder for updating CompletedUnblock entities.
type CompletedUnblockUpdate struct {
	config
	hooks    []Hook
	mutation *CompletedUnblockMutation
}

// Where appends a list predicates to the CompletedUnblockUpdate builder.
func (_u *CompletedUnblockUpdate) Where(ps ...predicate.CompletedUnblock) *CompletedUnblockUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *CompletedUnblockUpdate) SetType(v string) *CompletedUnblockUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CompletedUnblockUpdate) SetNillableType(v *string) *CompletedUnblockUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *CompletedUnblockUpdate) SetValue(v string) *CompletedUnblockUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *CompletedUnblockUpdate) SetNillableValue(v *string) *CompletedUnblockUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetTargetHostname sets the "target_hostname" field.
func (_u *CompletedUnblockUpdate) SetTargetHostname(v string) *CompletedUnblockUpdate {
	_u.mutation.SetTargetHostname(v)
	return _u
}

// SetNillableTargetHostname sets the "target_hostname" field if the given value is not nil.
func (_u *CompletedUnblockUpdate) SetNillableTargetHostname(v *string) *CompletedUnblockUpdate {
	if v != nil {
		_u.SetTargetHostname(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CompletedUnblockUpdate) SetCompletedAt(v int64) *CompletedUnblockUpdate {
	_u.mutation.ResetCompletedAt()
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CompletedUnblockUpdate) SetNillableCompletedAt(v *int64) *CompletedUnblockUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// AddCompletedAt adds value to the "completed_at" field.
func (_u *CompletedUnblockUpdate) AddCompletedAt(v int64) *CompletedUnblockUpdate {
	_u.mutation.AddCompletedAt(v)
	return _u
}

// Mutation returns the CompletedUnblockMutation object of the builder.
func (_u *CompletedUnblockUpdate) Mutation() *CompletedUnblockMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompletedUnblockUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompletedUnblockUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompletedUnblockUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompletedUnblockUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CompletedUnblockUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(completedunblock.Table, completedunblock.Columns, sqlgraph.NewFieldSpec(completedunblock.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(completedunblock.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(completedunblock.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetHostname(); ok {
		_spec.SetField(completedunblock.FieldTargetHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(completedunblock.FieldCompletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletedAt(); ok {
		_spec.AddField(completedunblock.FieldCompletedAt, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{completedunblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompletedUnblockUpdateOne is the builder for updating a single CompletedUnblock entity.
type CompletedUnblockUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompletedUnblockMutation
}

// SetType sets the "type" field.
func (_u *CompletedUnblockUpdateOne) SetType(v string) *CompletedUnblockUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CompletedUnblockUpdateOne) SetNillableType(v *string) *CompletedUnblockUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *CompletedUnblockUpdateOne) SetValue(v string) *CompletedUnblockUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *CompletedUnblockUpdateOne) SetNillableValue(v *string) *CompletedUnblockUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetTargetHostname sets the "target_hostname" field.
func (_u *CompletedUnblockUpdateOne) SetTargetHostname(v string) *CompletedUnblockUpdateOne {
	_u.mutation.SetTargetHostname(v)
	return _u
}

// SetNillableTargetHostname sets the "target_hostname" field if the given value is not nil.
func (_u *CompletedUnblockUpdateOne) SetNillableTargetHostname(v *string) *CompletedUnblockUpdateOne {
	if v != nil {
		_u.SetTargetHostname(*v)
	}
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *CompletedUnblockUpdateOne) SetCompletedAt(v int64) *CompletedUnblockUpdateOne {
	_u.mutation.ResetCompletedAt()
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *CompletedUnblockUpdateOne) SetNillableCompletedAt(v *int64) *CompletedUnblockUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// AddCompletedAt adds value to the "completed_at" field.
func (_u *CompletedUnblockUpdateOne) AddCompletedAt(v int64) *CompletedUnblockUpdateOne {
	_u.mutation.AddCompletedAt(v)
	return _u
}

// Mutation returns the CompletedUnblockMutation object of the builder.
func (_u *CompletedUnblockUpdateOne) Mutation() *CompletedUnblockMutation {
	return _u.mutation
}

// Where appends a list predicates to the CompletedUnblockUpdate builder.
func (_u *CompletedUnblockUpdateOne) Where(ps ...predicate.CompletedUnblock) *CompletedUnblockUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompletedUnblockUpdateOne) Select(field string, fields ...string) *CompletedUnblockUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CompletedUnblock entity.
func (_u *CompletedUnblockUpdateOne) Save(ctx context.Context) (*CompletedUnblock, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompletedUnblockUpdateOne) SaveX(ctx context.Context) *CompletedUnblock {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompletedUnblockUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompletedUnblockUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CompletedUnblockUpdateOne) sqlSave(ctx context.Context) (_node *CompletedUnblock, err error) {
	_spec := sqlgraph.NewUpdateSpec(completedunblock.Table, completedunblock.Columns, sqlgraph.NewFieldSpec(completedunblock.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CompletedUnblock.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, completedunblock.FieldID)
		for _, f := range fields {
			if !completedunblock.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != completedunblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(completedunblock.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(completedunblock.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetHostname(); ok {
		_spec.SetField(completedunblock.FieldTargetHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(completedunblock.FieldCompletedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCompletedAt(); ok {
		_spec.AddField(completedunblock.FieldCompletedAt, field.TypeInt64, value)
	}
	_node = &CompletedUnblock{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{completedunblock.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
