// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/group"
	"github.com/g0lab/g0efilter/dashboard/store/ent/instance"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// InstanceUpdate is the builder for updating Instance entities.
type InstanceUpdate struct {
	config
	hooks    []Hook
	mutation *InstanceMutation
}

// Where appends a list predicates to the InstanceUpdate builder.
func (_u *InstanceUpdate) Where(ps ...predicate.Instance) *InstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetHostname sets the "hostname" field.
func (_u *InstanceUpdate) SetHostname(v string) *InstanceUpdate {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableHostname(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *InstanceUpdate) SetGroupID(v string) *InstanceUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableGroupID(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *InstanceUpdate) ClearGroupID() *InstanceUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPolicyOverride sets the "policy_override" field.
func (_u *InstanceUpdate) SetPolicyOverride(v string) *InstanceUpdate {
	_u.mutation.SetPolicyOverride(v)
	return _u
}

// SetNillablePolicyOverride sets the "policy_override" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillablePolicyOverride(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetPolicyOverride(*v)
	}
	return _u
}

// ClearPolicyOverride clears the value of the "policy_override" field.
func (_u *InstanceUpdate) ClearPolicyOverride() *InstanceUpdate {
	_u.mutation.ClearPolicyOverride()
	return _u
}

// SetFilterMode sets the "filter_mode" field.
func (_u *InstanceUpdate) SetFilterMode(v string) *InstanceUpdate {
	_u.mutation.SetFilterMode(v)
	return _u
}

// SetNillableFilterMode sets the "filter_mode" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableFilterMode(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetFilterMode(*v)
	}
	return _u
}

// SetReportedVersion sets the "reported_version" field.
func (_u *InstanceUpdate) SetReportedVersion(v string) *InstanceUpdate {
	_u.mutation.SetReportedVersion(v)
	return _u
}

// SetNillableReportedVersion sets the "reported_version" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableReportedVersion(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetReportedVersion(*v)
	}
	return _u
}

// SetReportedHash sets the "reported_hash" field.
func (_u *InstanceUpdate) SetReportedHash(v string) *InstanceUpdate {
	_u.mutation.SetReportedHash(v)
	return _u
}

// SetNillableReportedHash sets the "reported_hash" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableReportedHash(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetReportedHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *InstanceUpdate) SetLastSeenAt(v int64) *InstanceUpdate {
	_u.mutation.ResetLastSeenAt()
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableLastSeenAt(v *int64) *InstanceUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// AddLastSeenAt adds value to the "last_seen_at" field.
func (_u *InstanceUpdate) AddLastSeenAt(v int64) *InstanceUpdate {
	_u.mutation.AddLastSeenAt(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InstanceUpdate) SetCreatedAt(v int64) *InstanceUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableCreatedAt(v *int64) *InstanceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *InstanceUpdate) AddCreatedAt(v int64) *InstanceUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *InstanceUpdate) SetGroup(v *Group) *InstanceUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the InstanceMutation object of the builder.
func (_u *InstanceUpdate) Mutation() *InstanceMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *InstanceUpdate) ClearGroup() *InstanceUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(instance.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.PolicyOverride(); ok {
		_spec.SetField(instance.FieldPolicyOverride, field.TypeString, value)
	}
	if _u.mutation.PolicyOverrideCleared() {
		_spec.ClearField(instance.FieldPolicyOverride, field.TypeString)
	}
	if value, ok := _u.mutation.FilterMode(); ok {
		_spec.SetField(instance.FieldFilterMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReportedVersion(); ok {
		_spec.SetField(instance.FieldReportedVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReportedHash(); ok {
		_spec.SetField(instance.FieldReportedHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(instance.FieldLastSeenAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastSeenAt(); ok {
		_spec.AddField(instance.FieldLastSeenAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(instance.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(instance.FieldCreatedAt, field.TypeInt64, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.GroupTable,
			Columns: []string{instance.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.GroupTable,
			Columns: []string{instance.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstanceUpdateOne is the builder for updating a single Instance entity.
type InstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstanceMutation
}

// SetHostname sets the "hostname" field.
func (_u *InstanceUpdateOne) SetHostname(v string) *InstanceUpdateOne {
	_u.mutation.SetHostname(v)
	return _u
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableHostname(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetHostname(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *InstanceUpdateOne) SetGroupID(v string) *InstanceUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableGroupID(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *InstanceUpdateOne) ClearGroupID() *InstanceUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetPolicyOverride sets the "policy_override" field.
func (_u *InstanceUpdateOne) SetPolicyOverride(v string) *InstanceUpdateOne {
	_u.mutation.SetPolicyOverride(v)
	return _u
}

// SetNillablePolicyOverride sets the "policy_override" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillablePolicyOverride(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetPolicyOverride(*v)
	}
	return _u
}

// ClearPolicyOverride clears the value of the "policy_override" field.
func (_u *InstanceUpdateOne) ClearPolicyOverride() *InstanceUpdateOne {
	_u.mutation.ClearPolicyOverride()
	return _u
}

// SetFilterMode sets the "filter_mode" field.
func (_u *InstanceUpdateOne) SetFilterMode(v string) *InstanceUpdateOne {
	_u.mutation.SetFilterMode(v)
	return _u
}

// SetNillableFilterMode sets the "filter_mode" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableFilterMode(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetFilterMode(*v)
	}
	return _u
}

// SetReportedVersion sets the "reported_version" field.
func (_u *InstanceUpdateOne) SetReportedVersion(v string) *InstanceUpdateOne {
	_u.mutation.SetReportedVersion(v)
	return _u
}

// SetNillableReportedVersion sets the "reported_version" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableReportedVersion(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetReportedVersion(*v)
	}
	return _u
}

// SetReportedHash sets the "reported_hash" field.
func (_u *InstanceUpdateOne) SetReportedHash(v string) *InstanceUpdateOne {
	_u.mutation.SetReportedHash(v)
	return _u
}

// SetNillableReportedHash sets the "reported_hash" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableReportedHash(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetReportedHash(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *InstanceUpdateOne) SetLastSeenAt(v int64) *InstanceUpdateOne {
	_u.mutation.ResetLastSeenAt()
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableLastSeenAt(v *int64) *InstanceUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// AddLastSeenAt adds value to the "last_seen_at" field.
func (_u *InstanceUpdateOne) AddLastSeenAt(v int64) *InstanceUpdateOne {
	_u.mutation.AddLastSeenAt(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *InstanceUpdateOne) SetCreatedAt(v int64) *InstanceUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableCreatedAt(v *int64) *InstanceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *InstanceUpdateOne) AddCreatedAt(v int64) *InstanceUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *InstanceUpdateOne) SetGroup(v *Group) *InstanceUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the InstanceMutation object of the builder.
func (_u *InstanceUpdateOne) Mutation() *InstanceMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *InstanceUpdateOne) ClearGroup() *InstanceUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the InstanceUpdate builder.
func (_u *InstanceUpdateOne) Where(ps ...predicate.Instance) *InstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstanceUpdateOne) Select(field string, fields ...string) *InstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Instance entity.
func (_u *InstanceUpdateOne) Save(ctx context.Context) (*Instance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceUpdateOne) SaveX(ctx context.Context) *Instance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InstanceUpdateOne) sqlSave(ctx context.Context) (_node *Instance, err error) {
	_spec := sqlgraph.NewUpdateSpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Instance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instance.FieldID)
		for _, f := range fields {
			if !instance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != instance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Hostname(); ok {
		_spec.SetField(instance.FieldHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.PolicyOverride(); ok {
		_spec.SetField(instance.FieldPolicyOverride, field.TypeString, value)
	}
	if _u.mutation.PolicyOverrideCleared() {
		_spec.ClearField(instance.FieldPolicyOverride, field.TypeString)
	}
	if value, ok := _u.mutation.FilterMode(); ok {
		_spec.SetField(instance.FieldFilterMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReportedVersion(); ok {
		_spec.SetField(instance.FieldReportedVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReportedHash(); ok {
		_spec.SetField(instance.FieldReportedHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(instance.FieldLastSeenAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastSeenAt(); ok {
		_spec.AddField(instance.FieldLastSeenAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(instance.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(instance.FieldCreatedAt, field.TypeInt64, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.GroupTable,
			Columns: []string{instance.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.GroupTable,
			Columns: []string{instance.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Instance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
