// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/group"
	"github.com/g0lab/g0efilter/dashboard/store/ent/instance"
)

// InstanceCreate is the builder for creating a Instance entity.
type InstanceCreate struct {
	config
	mutation *InstanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetHostname sets the "hostname" field.
func (_c *InstanceCreate) SetHostname(v string) *InstanceCreate {
	_c.mutation.SetHostname(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *InstanceCreate) SetGroupID(v string) *InstanceCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableGroupID(v *string) *InstanceCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetPolicyOverride sets the "policy_override" field.
func (_c *InstanceCreate) SetPolicyOverride(v string) *InstanceCreate {
	_c.mutation.SetPolicyOverride(v)
	return _c
}

// SetNillablePolicyOverride sets the "policy_override" field if the given value is not nil.
func (_c *InstanceCreate) SetNillablePolicyOverride(v *string) *InstanceCreate {
	if v != nil {
		_c.SetPolicyOverride(*v)
	}
	return _c
}

// SetFilterMode sets the "filter_mode" field.
func (_c *InstanceCreate) SetFilterMode(v string) *InstanceCreate {
	_c.mutation.SetFilterMode(v)
	return _c
}

// SetNillableFilterMode sets the "filter_mode" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableFilterMode(v *string) *InstanceCreate {
	if v != nil {
		_c.SetFilterMode(*v)
	}
	return _c
}

// SetReportedVersion sets the "reported_version" field.
func (_c *InstanceCreate) SetReportedVersion(v string) *InstanceCreate {
	_c.mutation.SetReportedVersion(v)
	return _c
}

// SetNillableReportedVersion sets the "reported_version" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableReportedVersion(v *string) *InstanceCreate {
	if v != nil {
		_c.SetReportedVersion(*v)
	}
	return _c
}

// SetReportedHash sets the "reported_hash" field.
func (_c *InstanceCreate) SetReportedHash(v string) *InstanceCreate {
	_c.mutation.SetReportedHash(v)
	return _c
}

// SetNillableReportedHash sets the "reported_hash" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableReportedHash(v *string) *InstanceCreate {
	if v != nil {
		_c.SetReportedHash(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *InstanceCreate) SetLastSeenAt(v int64) *InstanceCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *InstanceCreate) SetCreatedAt(v int64) *InstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *InstanceCreate) SetID(v string) *InstanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *InstanceCreate) SetGroup(v *Group) *InstanceCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the InstanceMutation object of the builder.
func (_c *InstanceCreate) Mutation() *InstanceMutation {
	return _c.mutation
}

// Save creates the Instance in the database.
func (_c *InstanceCreate) Save(ctx context.Context) (*Instance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InstanceCreate) SaveX(ctx context.Context) *Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InstanceCreate) defaults() {
	if _, ok := _c.mutation.FilterMode(); !ok {
		v := instance.DefaultFilterMode
		_c.mutation.SetFilterMode(v)
	}
	if _, ok := _c.mutation.ReportedVersion(); !ok {
		v := instance.DefaultReportedVersion
		_c.mutation.SetReportedVersion(v)
	}
	if _, ok := _c.mutation.ReportedHash(); !ok {
		v := instance.DefaultReportedHash
		_c.mutation.SetReportedHash(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InstanceCreate) check() error {
	if _, ok := _c.mutation.Hostname(); !ok {
		return &ValidationError{Name: "hostname", err: errors.New(`ent: missing required field "Instance.hostname"`)}
	}
	if _, ok := _c.mutation.FilterMode(); !ok {
		return &ValidationError{Name: "filter_mode", err: errors.New(`ent: missing required field "Instance.filter_mode"`)}
	}
	if _, ok := _c.mutation.ReportedVersion(); !ok {
		return &ValidationError{Name: "reported_version", err: errors.New(`ent: missing required field "Instance.reported_version"`)}
	}
	if _, ok := _c.mutation.ReportedHash(); !ok {
		return &ValidationError{Name: "reported_hash", err: errors.New(`ent: missing required field "Instance.reported_hash"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Instance.last_seen_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Instance.created_at"`)}
	}
	return nil
}

func (_c *InstanceCreate) sqlSave(ctx context.Context) (*Instance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Instance.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InstanceCreate) createSpec() (*Instance, *sqlgraph.CreateSpec) {
	var (
		_node = &Instance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(instance.Table, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Hostname(); ok {
		_spec.SetField(instance.FieldHostname, field.TypeString, value)
		_node.Hostname = value
	}
	if value, ok := _c.mutation.PolicyOverride(); ok {
		_spec.SetField(instance.FieldPolicyOverride, field.TypeString, value)
		_node.PolicyOverride = &value
	}
	if value, ok := _c.mutation.FilterMode(); ok {
		_spec.SetField(instance.FieldFilterMode, field.TypeString, value)
		_node.FilterMode = value
	}
	if value, ok := _c.mutation.ReportedVersion(); ok {
		_spec.SetField(instance.FieldReportedVersion, field.TypeString, value)
		_node.ReportedVersion = value
	}
	if value, ok := _c.mutation.ReportedHash(); ok {
		_spec.SetField(instance.FieldReportedHash, field.TypeString, value)
		_node.ReportedHash = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(instance.FieldLastSeenAt, field.TypeInt64, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(instance.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instance.GroupTable,
			Columns: []string{instance.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Instance.Create().
//		SetHostname(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InstanceUpsert) {
//			SetHostname(v+v).
//		}).
//		Exec(ctx)
func (_c *InstanceCreate) OnConflict(opts ...sql.ConflictOption) *InstanceUpsertOne {
	_c.conflict = opts
	return &InstanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InstanceCreate) OnConflictColumns(columns ...string) *InstanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InstanceUpsertOne{
		create: _c,
	}
}

type (
	// InstanceUpsertOne is the builder for "upsert"-ing
	//  one Instance node.
	InstanceUpsertOne struct {
		create *InstanceCreate
	}

	// InstanceUpsert is the "OnConflict" setter.
	InstanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetHostname sets the "hostname" field.
func (u *InstanceUpsert) SetHostname(v string) *InstanceUpsert {
	u.Set(instance.FieldHostname, v)
	return u
}

// UpdateHostname sets the "hostname" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateHostname() *InstanceUpsert {
	u.SetExcluded(instance.FieldHostname)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *InstanceUpsert) SetGroupID(v string) *InstanceUpsert {
	u.Set(instance.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateGroupID() *InstanceUpsert {
	u.SetExcluded(instance.FieldGroupID)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *InstanceUpsert) ClearGroupID() *InstanceUpsert {
	u.SetNull(instance.FieldGroupID)
	return u
}

// SetPolicyOverride sets the "policy_override" field.
func (u *InstanceUpsert) SetPolicyOverride(v string) *InstanceUpsert {
	u.Set(instance.FieldPolicyOverride, v)
	return u
}

// UpdatePolicyOverride sets the "policy_override" field to the value that was provided on create.
func (u *InstanceUpsert) UpdatePolicyOverride() *InstanceUpsert {
	u.SetExcluded(instance.FieldPolicyOverride)
	return u
}

// ClearPolicyOverride clears the value of the "policy_override" field.
func (u *InstanceUpsert) ClearPolicyOverride() *InstanceUpsert {
	u.SetNull(instance.FieldPolicyOverride)
	return u
}

// SetFilterMode sets the "filter_mode" field.
func (u *InstanceUpsert) SetFilterMode(v string) *InstanceUpsert {
	u.Set(instance.FieldFilterMode, v)
	return u
}

// UpdateFilterMode sets the "filter_mode" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateFilterMode() *InstanceUpsert {
	u.SetExcluded(instance.FieldFilterMode)
	return u
}

// SetReportedVersion sets the "reported_version" field.
func (u *InstanceUpsert) SetReportedVersion(v string) *InstanceUpsert {
	u.Set(instance.FieldReportedVersion, v)
	return u
}

// UpdateReportedVersion sets the "reported_version" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateReportedVersion() *InstanceUpsert {
	u.SetExcluded(instance.FieldReportedVersion)
	return u
}

// SetReportedHash sets the "reported_hash" field.
func (u *InstanceUpsert) SetReportedHash(v string) *InstanceUpsert {
	u.Set(instance.FieldReportedHash, v)
	return u
}

// UpdateReportedHash sets the "reported_hash" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateReportedHash() *InstanceUpsert {
	u.SetExcluded(instance.FieldReportedHash)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *InstanceUpsert) SetLastSeenAt(v int64) *InstanceUpsert {
	u.Set(instance.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateLastSeenAt() *InstanceUpsert {
	u.SetExcluded(instance.FieldLastSeenAt)
	return u
}

// AddLastSeenAt adds v to the "last_seen_at" field.
func (u *InstanceUpsert) AddLastSeenAt(v int64) *InstanceUpsert {
	u.Add(instance.FieldLastSeenAt, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *InstanceUpsert) SetCreatedAt(v int64) *InstanceUpsert {
	u.Set(instance.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateCreatedAt() *InstanceUpsert {
	u.SetExcluded(instance.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *InstanceUpsert) AddCreatedAt(v int64) *InstanceUpsert {
	u.Add(instance.FieldCreatedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(instance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InstanceUpsertOne) UpdateNewValues() *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(instance.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Instance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InstanceUpsertOne) Ignore() *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InstanceUpsertOne) DoNothing() *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InstanceCreate.OnConflict
// documentation for more info.
func (u *InstanceUpsertOne) Update(set func(*InstanceUpsert)) *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InstanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostname sets the "hostname" field.
func (u *InstanceUpsertOne) SetHostname(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetHostname(v)
	})
}

// UpdateHostname sets the "hostname" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateHostname() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateHostname()
	})
}

// SetGroupID sets the "group_id" field.
func (u *InstanceUpsertOne) SetGroupID(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateGroupID() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *InstanceUpsertOne) ClearGroupID() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.ClearGroupID()
	})
}

// SetPolicyOverride sets the "policy_override" field.
func (u *InstanceUpsertOne) SetPolicyOverride(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetPolicyOverride(v)
	})
}

// UpdatePolicyOverride sets the "policy_override" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdatePolicyOverride() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdatePolicyOverride()
	})
}

// ClearPolicyOverride clears the value of the "policy_override" field.
func (u *InstanceUpsertOne) ClearPolicyOverride() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.ClearPolicyOverride()
	})
}

// SetFilterMode sets the "filter_mode" field.
func (u *InstanceUpsertOne) SetFilterMode(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetFilterMode(v)
	})
}

// UpdateFilterMode sets the "filter_mode" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateFilterMode() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateFilterMode()
	})
}

// SetReportedVersion sets the "reported_version" field.
func (u *InstanceUpsertOne) SetReportedVersion(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetReportedVersion(v)
	})
}

// UpdateReportedVersion sets the "reported_version" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateReportedVersion() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateReportedVersion()
	})
}

// SetReportedHash sets the "reported_hash" field.
func (u *InstanceUpsertOne) SetReportedHash(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetReportedHash(v)
	})
}

// UpdateReportedHash sets the "reported_hash" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateReportedHash() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateReportedHash()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *InstanceUpsertOne) SetLastSeenAt(v int64) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// AddLastSeenAt adds v to the "last_seen_at" field.
func (u *InstanceUpsertOne) AddLastSeenAt(v int64) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.AddLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateLastSeenAt() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InstanceUpsertOne) SetCreatedAt(v int64) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *InstanceUpsertOne) AddCreatedAt(v int64) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateCreatedAt() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InstanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InstanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InstanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InstanceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InstanceUpsertOne.ID is not supported by MySQL driver. Use InstanceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InstanceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InstanceCreateBulk is the builder for creating many Instance entities in bulk.
type InstanceCreateBulk struct {
	config
	err      error
	builders []*InstanceCreate
	conflict []sql.ConflictOption
}

// Save creates the Instance entities in the database.
func (_c *InstanceCreateBulk) Save(ctx context.Context) ([]*Instance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Instance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InstanceCreateBulk) SaveX(ctx context.Context) []*Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Instance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InstanceUpsert) {
//			SetHostname(v+v).
//		}).
//		Exec(ctx)
func (_c *InstanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InstanceUpsertBulk {
	_c.conflict = opts
	return &InstanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InstanceCreateBulk) OnConflictColumns(columns ...string) *InstanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InstanceUpsertBulk{
		create: _c,
	}
}

// InstanceUpsertBulk is the builder for "upsert"-ing
// a bulk of Instance nodes.
type InstanceUpsertBulk struct {
	create *InstanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(instance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InstanceUpsertBulk) UpdateNewValues() *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(instance.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InstanceUpsertBulk) Ignore() *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InstanceUpsertBulk) DoNothing() *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InstanceCreateBulk.OnConflict
// documentation for more info.
func (u *InstanceUpsertBulk) Update(set func(*InstanceUpsert)) *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InstanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetHostname sets the "hostname" field.
func (u *InstanceUpsertBulk) SetHostname(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetHostname(v)
	})
}

// UpdateHostname sets the "hostname" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateHostname() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateHostname()
	})
}

// SetGroupID sets the "group_id" field.
func (u *InstanceUpsertBulk) SetGroupID(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateGroupID() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *InstanceUpsertBulk) ClearGroupID() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.ClearGroupID()
	})
}

// SetPolicyOverride sets the "policy_override" field.
func (u *InstanceUpsertBulk) SetPolicyOverride(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetPolicyOverride(v)
	})
}

// UpdatePolicyOverride sets the "policy_override" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdatePolicyOverride() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdatePolicyOverride()
	})
}

// ClearPolicyOverride clears the value of the "policy_override" field.
func (u *InstanceUpsertBulk) ClearPolicyOverride() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.ClearPolicyOverride()
	})
}

// SetFilterMode sets the "filter_mode" field.
func (u *InstanceUpsertBulk) SetFilterMode(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetFilterMode(v)
	})
}

// UpdateFilterMode sets the "filter_mode" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateFilterMode() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateFilterMode()
	})
}

// SetReportedVersion sets the "reported_version" field.
func (u *InstanceUpsertBulk) SetReportedVersion(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetReportedVersion(v)
	})
}

// UpdateReportedVersion sets the "reported_version" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateReportedVersion() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateReportedVersion()
	})
}

// SetReportedHash sets the "reported_hash" field.
func (u *InstanceUpsertBulk) SetReportedHash(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetReportedHash(v)
	})
}

// UpdateReportedHash sets the "reported_hash" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateReportedHash() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateReportedHash()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *InstanceUpsertBulk) SetLastSeenAt(v int64) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetLastSeenAt(v)
	})
}

// AddLastSeenAt adds v to the "last_seen_at" field.
func (u *InstanceUpsertBulk) AddLastSeenAt(v int64) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.AddLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateLastSeenAt() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *InstanceUpsertBulk) SetCreatedAt(v int64) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *InstanceUpsertBulk) AddCreatedAt(v int64) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateCreatedAt() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *InstanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InstanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InstanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InstanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
