// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/logevent"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// LogEventUpdate is the builder for updating LogEvent entities.
type LogEventUpdate struct {
	config
	hooks    []Hook
	mutation *LogEventMutation
}

// Where appends a list predicates to the LogEventUpdate builder.
func (_u *LogEventUpdate) Where(ps ...predicate.LogEvent) *LogEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTs sets the "ts" field.
func (_u *LogEventUpdate) SetTs(v int64) *LogEventUpdate {
	_u.mutation.ResetTs()
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *LogEventUpdate) SetNillableTs(v *int64) *LogEventUpdate {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// AddTs adds value to the "ts" field.
func (_u *LogEventUpdate) AddTs(v int64) *LogEventUpdate {
	_u.mutation.AddTs(v)
	return _u
}

// SetData sets the "data" field.
func (_u *LogEventUpdate) SetData(v string) *LogEventUpdate {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *LogEventUpdate) SetNillableData(v *string) *LogEventUpdate {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// SetSearch sets the "search" field.
func (_u *LogEventUpdate) SetSearch(v string) *LogEventUpdate {
	_u.mutation.SetSearch(v)
	return _u
}

// SetNillableSearch sets the "search" field if the given value is not nil.
func (_u *LogEventUpdate) SetNillableSearch(v *string) *LogEventUpdate {
	if v != nil {
		_u.SetSearch(*v)
	}
	return _u
}

// Mutation returns the LogEventMutation object of the builder.
func (_u *LogEventUpdate) Mutation() *LogEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LogEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LogEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LogEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(logevent.Table, logevent.Columns, sqlgraph.NewFieldSpec(logevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(logevent.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTs(); ok {
		_spec.AddField(logevent.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(logevent.FieldData, field.TypeString, value)
	}
	if value, ok := _u.mutation.Search(); ok {
		_spec.SetField(logevent.FieldSearch, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LogEventUpdateOne is the builder for updating a single LogEvent entity.
type LogEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LogEventMutation
}

// SetTs sets the "ts" field.
func (_u *LogEventUpdateOne) SetTs(v int64) *LogEventUpdateOne {
	_u.mutation.ResetTs()
	_u.mutation.SetTs(v)
	return _u
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_u *LogEventUpdateOne) SetNillableTs(v *int64) *LogEventUpdateOne {
	if v != nil {
		_u.SetTs(*v)
	}
	return _u
}

// AddTs adds value to the "ts" field.
func (_u *LogEventUpdateOne) AddTs(v int64) *LogEventUpdateOne {
	_u.mutation.AddTs(v)
	return _u
}

// SetData sets the "data" field.
func (_u *LogEventUpdateOne) SetData(v string) *LogEventUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// SetNillableData sets the "data" field if the given value is not nil.
func (_u *LogEventUpdateOne) SetNillableData(v *string) *LogEventUpdateOne {
	if v != nil {
		_u.SetData(*v)
	}
	return _u
}

// SetSearch sets the "search" field.
func (_u *LogEventUpdateOne) SetSearch(v string) *LogEventUpdateOne {
	_u.mutation.SetSearch(v)
	return _u
}

// SetNillableSearch sets the "search" field if the given value is not nil.
func (_u *LogEventUpdateOne) SetNillableSearch(v *string) *LogEventUpdateOne {
	if v != nil {
		_u.SetSearch(*v)
	}
	return _u
}

// Mutation returns the LogEventMutation object of the builder.
func (_u *LogEventUpdateOne) Mutation() *LogEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the LogEventUpdate builder.
func (_u *LogEventUpdateOne) Where(ps ...predicate.LogEvent) *LogEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LogEventUpdateOne) Select(field string, fields ...string) *LogEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LogEvent entity.
func (_u *LogEventUpdateOne) Save(ctx context.Context) (*LogEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogEventUpdateOne) SaveX(ctx context.Context) *LogEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LogEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *LogEventUpdateOne) sqlSave(ctx context.Context) (_node *LogEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(logevent.Table, logevent.Columns, sqlgraph.NewFieldSpec(logevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LogEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logevent.FieldID)
		for _, f := range fields {
			if !logevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ts(); ok {
		_spec.SetField(logevent.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTs(); ok {
		_spec.AddField(logevent.FieldTs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(logevent.FieldData, field.TypeString, value)
	}
	if value, ok := _u.mutation.Search(); ok {
		_spec.SetField(logevent.FieldSearch, field.TypeString, value)
	}
	_node = &LogEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
