// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/g0lab/g0efilter/dashboard/store/ent/logevent"
)

// LogEvent is the model entity for the LogEvent schema.
type LogEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ts holds the value of the "ts" field.
	Ts int64 `json:"ts,omitempty"`
	// Data holds the value of the "data" field.
	Data string `json:"data,omitempty"`
	// Search holds the value of the "search" field.
	Search       string `json:"search,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LogEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case logevent.FieldID, logevent.FieldTs:
			values[i] = new(sql.NullInt64)
		case logevent.FieldData, logevent.FieldSearch:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LogEvent fields.
func (_m *LogEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case logevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case logevent.FieldTs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ts", values[i])
			} else if value.Valid {
				_m.Ts = value.Int64
			}
		case logevent.FieldData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value.Valid {
				_m.Data = value.String
			}
		case logevent.FieldSearch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field search", values[i])
			} else if value.Valid {
				_m.Search = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LogEvent.
// This includes values selected through modifiers, order, etc.
func (_m *LogEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LogEvent.
// Note that you need to call LogEvent.Unwrap() before calling this method if this LogEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LogEvent) Update() *LogEventUpdateOne {
	return NewLogEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LogEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LogEvent) Unwrap() *LogEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LogEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LogEvent) String() string {
	var builder strings.Builder
	builder.WriteString("LogEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ts))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(_m.Data)
	builder.WriteString(", ")
	builder.WriteString("search=")
	builder.WriteString(_m.Search)
	builder.WriteByte(')')
	return builder.String()
}

// LogEvents is a parsable slice of LogEvent.
type LogEvents []*LogEvent
