// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/g0lab/g0efilter/dashboard/store/ent/completedunblock"
	"github.com/g0lab/g0efilter/dashboard/store/ent/group"
	"github.com/g0lab/g0efilter/dashboard/store/ent/instance"
	"github.com/g0lab/g0efilter/dashboard/store/ent/schema"
	"github.com/g0lab/g0efilter/dashboard/store/ent/unblockrequest"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	completedunblockFields := schema.CompletedUnblock{}.Fields()
	_ = completedunblockFields
	// completedunblockDescTargetHostname is the schema descriptor for target_hostname field.
	completedunblockDescTargetHostname := completedunblockFields[2].Descriptor()
	// completedunblock.DefaultTargetHostname holds the default value on creation for the target_hostname field.
	completedunblock.DefaultTargetHostname = completedunblockDescTargetHostname.Default.(string)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescPolicy is the schema descriptor for policy field.
	groupDescPolicy := groupFields[2].Descriptor()
	// group.DefaultPolicy holds the default value on creation for the policy field.
	group.DefaultPolicy = groupDescPolicy.Default.(string)
	// groupDescFilterMode is the schema descriptor for filter_mode field.
	groupDescFilterMode := groupFields[3].Descriptor()
	// group.DefaultFilterMode holds the default value on creation for the filter_mode field.
	group.DefaultFilterMode = groupDescFilterMode.Default.(string)
	instanceFields := schema.Instance{}.Fields()
	_ = instanceFields
	// instanceDescFilterMode is the schema descriptor for filter_mode field.
	instanceDescFilterMode := instanceFields[4].Descriptor()
	// instance.DefaultFilterMode holds the default value on creation for the filter_mode field.
	instance.DefaultFilterMode = instanceDescFilterMode.Default.(string)
	// instanceDescReportedVersion is the schema descriptor for reported_version field.
	instanceDescReportedVersion := instanceFields[5].Descriptor()
	// instance.DefaultReportedVersion holds the default value on creation for the reported_version field.
	instance.DefaultReportedVersion = instanceDescReportedVersion.Default.(string)
	// instanceDescReportedHash is the schema descriptor for reported_hash field.
	instanceDescReportedHash := instanceFields[6].Descriptor()
	// instance.DefaultReportedHash holds the default value on creation for the reported_hash field.
	instance.DefaultReportedHash = instanceDescReportedHash.Default.(string)
	unblockrequestFields := schema.UnblockRequest{}.Fields()
	_ = unblockrequestFields
	// unblockrequestDescTargetHostname is the schema descriptor for target_hostname field.
	unblockrequestDescTargetHostname := unblockrequestFields[3].Descriptor()
	// unblockrequest.DefaultTargetHostname holds the default value on creation for the target_hostname field.
	unblockrequest.DefaultTargetHostname = unblockrequestDescTargetHostname.Default.(string)
}
