// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
	"github.com/g0lab/g0efilter/dashboard/store/ent/unblockrequest"
)

// UnblockRequestUpdate is the builder for updating UnblockRequest entities.
type UnblockRequestUpdate struct {
	config
	hooks    []Hook
	mutation *UnblockRequestMutation
}

// Where appends a list predicates to the UnblockRequestUpdate builder.
func (_u *UnblockRequestUpdate) Where(ps ...predicate.UnblockRequest) *UnblockRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *UnblockRequestUpdate) SetType(v string) *UnblockRequestUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UnblockRequestUpdate) SetNillableType(v *string) *UnblockRequestUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *UnblockRequestUpdate) SetValue(v string) *UnblockRequestUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *UnblockRequestUpdate) SetNillableValue(v *string) *UnblockRequestUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetTargetHostname sets the "target_hostname" field.
func (_u *UnblockRequestUpdate) SetTargetHostname(v string) *UnblockRequestUpdate {
	_u.mutation.SetTargetHostname(v)
	return _u
}

// SetNillableTargetHostname sets the "target_hostname" field if the given value is not nil.
func (_u *UnblockRequestUpdate) SetNillableTargetHostname(v *string) *UnblockRequestUpdate {
	if v != nil {
		_u.SetTargetHostname(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UnblockRequestUpdate) SetCreatedAt(v int64) *UnblockRequestUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UnblockRequestUpdate) SetNillableCreatedAt(v *int64) *UnblockRequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *UnblockRequestUpdate) AddCreatedAt(v int64) *UnblockRequestUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// Mutation returns the UnblockRequestMutation object of the builder.
func (_u *UnblockRequestUpdate) Mutation() *UnblockRequestMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UnblockRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnblockRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UnblockRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnblockRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UnblockRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(unblockrequest.Table, unblockrequest.Columns, sqlgraph.NewFieldSpec(unblockrequest.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(unblockrequest.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(unblockrequest.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetHostname(); ok {
		_spec.SetField(unblockrequest.FieldTargetHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(unblockrequest.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(unblockrequest.FieldCreatedAt, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unblockrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UnblockRequestUpdateOne is the builder for updating a single UnblockRequest entity.
type UnblockRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UnblockRequestMutation
}

// SetType sets the "type" field.
func (_u *UnblockRequestUpdateOne) SetType(v string) *UnblockRequestUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UnblockRequestUpdateOne) SetNillableType(v *string) *UnblockRequestUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *UnblockRequestUpdateOne) SetValue(v string) *UnblockRequestUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *UnblockRequestUpdateOne) SetNillableValue(v *string) *UnblockRequestUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetTargetHostname sets the "target_hostname" field.
func (_u *UnblockRequestUpdateOne) SetTargetHostname(v string) *UnblockRequestUpdateOne {
	_u.mutation.SetTargetHostname(v)
	return _u
}

// SetNillableTargetHostname sets the "target_hostname" field if the given value is not nil.
func (_u *UnblockRequestUpdateOne) SetNillableTargetHostname(v *string) *UnblockRequestUpdateOne {
	if v != nil {
		_u.SetTargetHostname(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UnblockRequestUpdateOne) SetCreatedAt(v int64) *UnblockRequestUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UnblockRequestUpdateOne) SetNillableCreatedAt(v *int64) *UnblockRequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *UnblockRequestUpdateOne) AddCreatedAt(v int64) *UnblockRequestUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// Mutation returns the UnblockRequestMutation object of the builder.
func (_u *UnblockRequestUpdateOne) Mutation() *UnblockRequestMutation {
	return _u.mutation
}

// Where appends a list predicates to the UnblockRequestUpdate builder.
func (_u *UnblockRequestUpdateOne) Where(ps ...predicate.UnblockRequest) *UnblockRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UnblockRequestUpdateOne) Select(field string, fields ...string) *UnblockRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UnblockRequest entity.
func (_u *UnblockRequestUpdateOne) Save(ctx context.Context) (*UnblockRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UnblockRequestUpdateOne) SaveX(ctx context.Context) *UnblockRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UnblockRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UnblockRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UnblockRequestUpdateOne) sqlSave(ctx context.Context) (_node *UnblockRequest, err error) {
	_spec := sqlgraph.NewUpdateSpec(unblockrequest.Table, unblockrequest.Columns, sqlgraph.NewFieldSpec(unblockrequest.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UnblockRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, unblockrequest.FieldID)
		for _, f := range fields {
			if !unblockrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != unblockrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(unblockrequest.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(unblockrequest.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetHostname(); ok {
		_spec.SetField(unblockrequest.FieldTargetHostname, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(unblockrequest.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(unblockrequest.FieldCreatedAt, field.TypeInt64, value)
	}
	_node = &UnblockRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{unblockrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
