// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "label", Type: field.TypeString},
		{Name: "key_hash", Type: field.TypeBytes, Unique: true},
		{Name: "key_prefix", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "last_used_at", Type: field.TypeInt64, Nullable: true},
		{Name: "revoked_at", Type: field.TypeInt64, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
	}
	// CompletedUnblocksColumns holds the columns for the "completed_unblocks" table.
	CompletedUnblocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "target_hostname", Type: field.TypeString, Default: ""},
		{Name: "completed_at", Type: field.TypeInt64},
	}
	// CompletedUnblocksTable holds the schema information for the "completed_unblocks" table.
	CompletedUnblocksTable = &schema.Table{
		Name:       "completed_unblocks",
		Columns:    CompletedUnblocksColumns,
		PrimaryKey: []*schema.Column{CompletedUnblocksColumns[0]},
	}
	// FleetGroupsColumns holds the columns for the "fleet_groups" table.
	FleetGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "policy", Type: field.TypeString, Default: ""},
		{Name: "filter_mode", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeInt64},
	}
	// FleetGroupsTable holds the schema information for the "fleet_groups" table.
	FleetGroupsTable = &schema.Table{
		Name:       "fleet_groups",
		Columns:    FleetGroupsColumns,
		PrimaryKey: []*schema.Column{FleetGroupsColumns[0]},
	}
	// FleetInstancesColumns holds the columns for the "fleet_instances" table.
	FleetInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "hostname", Type: field.TypeString, Unique: true},
		{Name: "policy_override", Type: field.TypeString, Nullable: true},
		{Name: "filter_mode", Type: field.TypeString, Default: ""},
		{Name: "reported_version", Type: field.TypeString, Default: ""},
		{Name: "reported_hash", Type: field.TypeString, Default: ""},
		{Name: "last_seen_at", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeString, Nullable: true},
	}
	// FleetInstancesTable holds the schema information for the "fleet_instances" table.
	FleetInstancesTable = &schema.Table{
		Name:       "fleet_instances",
		Columns:    FleetInstancesColumns,
		PrimaryKey: []*schema.Column{FleetInstancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "fleet_instances_fleet_groups_instances",
				Columns:    []*schema.Column{FleetInstancesColumns[8]},
				RefColumns: []*schema.Column{FleetGroupsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "instance_group_id",
				Unique:  false,
				Columns: []*schema.Column{FleetInstancesColumns[8]},
			},
		},
	}
	// LogsColumns holds the columns for the "logs" table.
	LogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ts", Type: field.TypeInt64},
		{Name: "data", Type: field.TypeString, Size: 2147483647},
		{Name: "search", Type: field.TypeString, Size: 2147483647},
	}
	// LogsTable holds the schema information for the "logs" table.
	LogsTable = &schema.Table{
		Name:       "logs",
		Columns:    LogsColumns,
		PrimaryKey: []*schema.Column{LogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "logevent_ts",
				Unique:  false,
				Columns: []*schema.Column{LogsColumns[1]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeBytes, Unique: true},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "expires_at", Type: field.TypeInt64},
		{Name: "user_id", Type: field.TypeString},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_expires_at",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[3]},
			},
		},
	}
	// UnblockRequestsColumns holds the columns for the "unblock_requests" table.
	UnblockRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "value", Type: field.TypeString},
		{Name: "target_hostname", Type: field.TypeString, Default: ""},
		{Name: "created_at", Type: field.TypeInt64},
	}
	// UnblockRequestsTable holds the schema information for the "unblock_requests" table.
	UnblockRequestsTable = &schema.Table{
		Name:       "unblock_requests",
		Columns:    UnblockRequestsColumns,
		PrimaryKey: []*schema.Column{UnblockRequestsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "unblockrequest_type_value_target_hostname",
				Unique:  true,
				Columns: []*schema.Column{UnblockRequestsColumns[1], UnblockRequestsColumns[2], UnblockRequestsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeInt64},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		CompletedUnblocksTable,
		FleetGroupsTable,
		FleetInstancesTable,
		LogsTable,
		SessionsTable,
		UnblockRequestsTable,
		UsersTable,
	}
)

func init() {
	APIKeysTable.Annotation = &entsql.Annotation{
		Table: "api_keys",
	}
	CompletedUnblocksTable.Annotation = &entsql.Annotation{
		Table: "completed_unblocks",
	}
	FleetGroupsTable.Annotation = &entsql.Annotation{
		Table: "fleet_groups",
	}
	FleetInstancesTable.ForeignKeys[0].RefTable = FleetGroupsTable
	FleetInstancesTable.Annotation = &entsql.Annotation{
		Table: "fleet_instances",
	}
	LogsTable.Annotation = &entsql.Annotation{
		Table: "logs",
	}
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	SessionsTable.Annotation = &entsql.Annotation{
		Table: "sessions",
	}
	UnblockRequestsTable.Annotation = &entsql.Annotation{
		Table: "unblock_requests",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
