// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/apikey"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/predicate"
)

// APIKeyUpdate is the builder for updating APIKey entities.
type APIKeyUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyMutation
}

// Where appends a list predicates to the APIKeyUpdate builder.
func (_u *APIKeyUpdate) Where(ps ...predicate.APIKey) *APIKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLabel sets the "label" field.
func (_u *APIKeyUpdate) SetLabel(v string) *APIKeyUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableLabel(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *APIKeyUpdate) SetKeyHash(v []byte) *APIKeyUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *APIKeyUpdate) SetKeyPrefix(v string) *APIKeyUpdate {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableKeyPrefix(v *string) *APIKeyUpdate {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *APIKeyUpdate) SetCreatedAt(v int64) *APIKeyUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableCreatedAt(v *int64) *APIKeyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *APIKeyUpdate) AddCreatedAt(v int64) *APIKeyUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *APIKeyUpdate) SetLastUsedAt(v int64) *APIKeyUpdate {
	_u.mutation.ResetLastUsedAt()
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableLastUsedAt(v *int64) *APIKeyUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// AddLastUsedAt adds value to the "last_used_at" field.
func (_u *APIKeyUpdate) AddLastUsedAt(v int64) *APIKeyUpdate {
	_u.mutation.AddLastUsedAt(v)
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *APIKeyUpdate) ClearLastUsedAt() *APIKeyUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *APIKeyUpdate) SetRevokedAt(v int64) *APIKeyUpdate {
	_u.mutation.ResetRevokedAt()
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *APIKeyUpdate) SetNillableRevokedAt(v *int64) *APIKeyUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// AddRevokedAt adds value to the "revoked_at" field.
func (_u *APIKeyUpdate) AddRevokedAt(v int64) *APIKeyUpdate {
	_u.mutation.AddRevokedAt(v)
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *APIKeyUpdate) ClearRevokedAt() *APIKeyUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the APIKeyMutation object of the builder.
func (_u *APIKeyUpdate) Mutation() *APIKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *APIKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(apikey.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(apikey.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(apikey.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastUsedAt(); ok {
		_spec.AddField(apikey.FieldLastUsedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevokedAt(); ok {
		_spec.AddField(apikey.FieldRevokedAt, field.TypeInt64, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(apikey.FieldRevokedAt, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyUpdateOne is the builder for updating a single APIKey entity.
type APIKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyMutation
}

// SetLabel sets the "label" field.
func (_u *APIKeyUpdateOne) SetLabel(v string) *APIKeyUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableLabel(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *APIKeyUpdateOne) SetKeyHash(v []byte) *APIKeyUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// SetKeyPrefix sets the "key_prefix" field.
func (_u *APIKeyUpdateOne) SetKeyPrefix(v string) *APIKeyUpdateOne {
	_u.mutation.SetKeyPrefix(v)
	return _u
}

// SetNillableKeyPrefix sets the "key_prefix" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableKeyPrefix(v *string) *APIKeyUpdateOne {
	if v != nil {
		_u.SetKeyPrefix(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *APIKeyUpdateOne) SetCreatedAt(v int64) *APIKeyUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableCreatedAt(v *int64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *APIKeyUpdateOne) AddCreatedAt(v int64) *APIKeyUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *APIKeyUpdateOne) SetLastUsedAt(v int64) *APIKeyUpdateOne {
	_u.mutation.ResetLastUsedAt()
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableLastUsedAt(v *int64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// AddLastUsedAt adds value to the "last_used_at" field.
func (_u *APIKeyUpdateOne) AddLastUsedAt(v int64) *APIKeyUpdateOne {
	_u.mutation.AddLastUsedAt(v)
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *APIKeyUpdateOne) ClearLastUsedAt() *APIKeyUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *APIKeyUpdateOne) SetRevokedAt(v int64) *APIKeyUpdateOne {
	_u.mutation.ResetRevokedAt()
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *APIKeyUpdateOne) SetNillableRevokedAt(v *int64) *APIKeyUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// AddRevokedAt adds value to the "revoked_at" field.
func (_u *APIKeyUpdateOne) AddRevokedAt(v int64) *APIKeyUpdateOne {
	_u.mutation.AddRevokedAt(v)
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *APIKeyUpdateOne) ClearRevokedAt() *APIKeyUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the APIKeyMutation object of the builder.
func (_u *APIKeyUpdateOne) Mutation() *APIKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the APIKeyUpdate builder.
func (_u *APIKeyUpdateOne) Where(ps ...predicate.APIKey) *APIKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyUpdateOne) Select(field string, fields ...string) *APIKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKey entity.
func (_u *APIKeyUpdateOne) Save(ctx context.Context) (*APIKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyUpdateOne) SaveX(ctx context.Context) *APIKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *APIKeyUpdateOne) sqlSave(ctx context.Context) (_node *APIKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(apikey.Table, apikey.Columns, sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikey.FieldID)
		for _, f := range fields {
			if !apikey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(apikey.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(apikey.FieldKeyHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.KeyPrefix(); ok {
		_spec.SetField(apikey.FieldKeyPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(apikey.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(apikey.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(apikey.FieldLastUsedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastUsedAt(); ok {
		_spec.AddField(apikey.FieldLastUsedAt, field.TypeInt64, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(apikey.FieldLastUsedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(apikey.FieldRevokedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevokedAt(); ok {
		_spec.AddField(apikey.FieldRevokedAt, field.TypeInt64, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(apikey.FieldRevokedAt, field.TypeInt64)
	}
	_node = &APIKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
