// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/logevent"
)

// LogEventCreate is the builder for creating a LogEvent entity.
type LogEventCreate struct {
	config
	mutation *LogEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTs sets the "ts" field.
func (_c *LogEventCreate) SetTs(v int64) *LogEventCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetData sets the "data" field.
func (_c *LogEventCreate) SetData(v string) *LogEventCreate {
	_c.mutation.SetData(v)
	return _c
}

// SetSearch sets the "search" field.
func (_c *LogEventCreate) SetSearch(v string) *LogEventCreate {
	_c.mutation.SetSearch(v)
	return _c
}

// Mutation returns the LogEventMutation object of the builder.
func (_c *LogEventCreate) Mutation() *LogEventMutation {
	return _c.mutation
}

// Save creates the LogEvent in the database.
func (_c *LogEventCreate) Save(ctx context.Context) (*LogEvent, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LogEventCreate) SaveX(ctx context.Context) *LogEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LogEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LogEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LogEventCreate) check() error {
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "LogEvent.ts"`)}
	}
	if _, ok := _c.mutation.Data(); !ok {
		return &ValidationError{Name: "data", err: errors.New(`ent: missing required field "LogEvent.data"`)}
	}
	if _, ok := _c.mutation.Search(); !ok {
		return &ValidationError{Name: "search", err: errors.New(`ent: missing required field "LogEvent.search"`)}
	}
	return nil
}

func (_c *LogEventCreate) sqlSave(ctx context.Context) (*LogEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LogEventCreate) createSpec() (*LogEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &LogEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(logevent.Table, sqlgraph.NewFieldSpec(logevent.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(logevent.FieldTs, field.TypeInt64, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.Data(); ok {
		_spec.SetField(logevent.FieldData, field.TypeString, value)
		_node.Data = value
	}
	if value, ok := _c.mutation.Search(); ok {
		_spec.SetField(logevent.FieldSearch, field.TypeString, value)
		_node.Search = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LogEvent.Create().
//		SetTs(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LogEventUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *LogEventCreate) OnConflict(opts ...sql.ConflictOption) *LogEventUpsertOne {
	_c.conflict = opts
	return &LogEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LogEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LogEventCreate) OnConflictColumns(columns ...string) *LogEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LogEventUpsertOne{
		create: _c,
	}
}

type (
	// LogEventUpsertOne is the builder for "upsert"-ing
	//  one LogEvent node.
	LogEventUpsertOne struct {
		create *LogEventCreate
	}

	// LogEventUpsert is the "OnConflict" setter.
	LogEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetTs sets the "ts" field.
func (u *LogEventUpsert) SetTs(v int64) *LogEventUpsert {
	u.Set(logevent.FieldTs, v)
	return u
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *LogEventUpsert) UpdateTs() *LogEventUpsert {
	u.SetExcluded(logevent.FieldTs)
	return u
}

// AddTs adds v to the "ts" field.
func (u *LogEventUpsert) AddTs(v int64) *LogEventUpsert {
	u.Add(logevent.FieldTs, v)
	return u
}

// SetData sets the "data" field.
func (u *LogEventUpsert) SetData(v string) *LogEventUpsert {
	u.Set(logevent.FieldData, v)
	return u
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *LogEventUpsert) UpdateData() *LogEventUpsert {
	u.SetExcluded(logevent.FieldData)
	return u
}

// SetSearch sets the "search" field.
func (u *LogEventUpsert) SetSearch(v string) *LogEventUpsert {
	u.Set(logevent.FieldSearch, v)
	return u
}

// UpdateSearch sets the "search" field to the value that was provided on create.
func (u *LogEventUpsert) UpdateSearch() *LogEventUpsert {
	u.SetExcluded(logevent.FieldSearch)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LogEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LogEventUpsertOne) UpdateNewValues() *LogEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LogEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LogEventUpsertOne) Ignore() *LogEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LogEventUpsertOne) DoNothing() *LogEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LogEventCreate.OnConflict
// documentation for more info.
func (u *LogEventUpsertOne) Update(set func(*LogEventUpsert)) *LogEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LogEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTs sets the "ts" field.
func (u *LogEventUpsertOne) SetTs(v int64) *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *LogEventUpsertOne) AddTs(v int64) *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *LogEventUpsertOne) UpdateTs() *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.UpdateTs()
	})
}

// SetData sets the "data" field.
func (u *LogEventUpsertOne) SetData(v string) *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *LogEventUpsertOne) UpdateData() *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.UpdateData()
	})
}

// SetSearch sets the "search" field.
func (u *LogEventUpsertOne) SetSearch(v string) *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.SetSearch(v)
	})
}

// UpdateSearch sets the "search" field to the value that was provided on create.
func (u *LogEventUpsertOne) UpdateSearch() *LogEventUpsertOne {
	return u.Update(func(s *LogEventUpsert) {
		s.UpdateSearch()
	})
}

// Exec executes the query.
func (u *LogEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LogEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LogEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LogEventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LogEventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LogEventCreateBulk is the builder for creating many LogEvent entities in bulk.
type LogEventCreateBulk struct {
	config
	err      error
	builders []*LogEventCreate
	conflict []sql.ConflictOption
}

// Save creates the LogEvent entities in the database.
func (_c *LogEventCreateBulk) Save(ctx context.Context) ([]*LogEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LogEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LogEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LogEventCreateBulk) SaveX(ctx context.Context) []*LogEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LogEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LogEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LogEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LogEventUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *LogEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *LogEventUpsertBulk {
	_c.conflict = opts
	return &LogEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LogEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LogEventCreateBulk) OnConflictColumns(columns ...string) *LogEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LogEventUpsertBulk{
		create: _c,
	}
}

// LogEventUpsertBulk is the builder for "upsert"-ing
// a bulk of LogEvent nodes.
type LogEventUpsertBulk struct {
	create *LogEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LogEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LogEventUpsertBulk) UpdateNewValues() *LogEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LogEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LogEventUpsertBulk) Ignore() *LogEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LogEventUpsertBulk) DoNothing() *LogEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LogEventCreateBulk.OnConflict
// documentation for more info.
func (u *LogEventUpsertBulk) Update(set func(*LogEventUpsert)) *LogEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LogEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetTs sets the "ts" field.
func (u *LogEventUpsertBulk) SetTs(v int64) *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.SetTs(v)
	})
}

// AddTs adds v to the "ts" field.
func (u *LogEventUpsertBulk) AddTs(v int64) *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.AddTs(v)
	})
}

// UpdateTs sets the "ts" field to the value that was provided on create.
func (u *LogEventUpsertBulk) UpdateTs() *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.UpdateTs()
	})
}

// SetData sets the "data" field.
func (u *LogEventUpsertBulk) SetData(v string) *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.SetData(v)
	})
}

// UpdateData sets the "data" field to the value that was provided on create.
func (u *LogEventUpsertBulk) UpdateData() *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.UpdateData()
	})
}

// SetSearch sets the "search" field.
func (u *LogEventUpsertBulk) SetSearch(v string) *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.SetSearch(v)
	})
}

// UpdateSearch sets the "search" field to the value that was provided on create.
func (u *LogEventUpsertBulk) UpdateSearch() *LogEventUpsertBulk {
	return u.Update(func(s *LogEventUpsert) {
		s.UpdateSearch()
	})
}

// Exec executes the query.
func (u *LogEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LogEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LogEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LogEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
