// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/predicate"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/session"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/user"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTokenHash sets the "token_hash" field.
func (_u *SessionUpdate) SetTokenHash(v []byte) *SessionUpdate {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdate) SetUserID(v string) *SessionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserID(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SessionUpdate) SetCreatedAt(v int64) *SessionUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableCreatedAt(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *SessionUpdate) AddCreatedAt(v int64) *SessionUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SessionUpdate) SetExpiresAt(v int64) *SessionUpdate {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableExpiresAt(v *int64) *SessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expires_at" field.
func (_u *SessionUpdate) AddExpiresAt(v int64) *SessionUpdate {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *SessionUpdate) SetOwnerID(id string) *SessionUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *SessionUpdate) SetOwner(v *User) *SessionUpdate {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *SessionUpdate) ClearOwner() *SessionUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdate) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.owner"`)
	}
	return nil
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(session.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(session.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(session.FieldExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetTokenHash sets the "token_hash" field.
func (_u *SessionUpdateOne) SetTokenHash(v []byte) *SessionUpdateOne {
	_u.mutation.SetTokenHash(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdateOne) SetUserID(v string) *SessionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserID(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *SessionUpdateOne) SetCreatedAt(v int64) *SessionUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableCreatedAt(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *SessionUpdateOne) AddCreatedAt(v int64) *SessionUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *SessionUpdateOne) SetExpiresAt(v int64) *SessionUpdateOne {
	_u.mutation.ResetExpiresAt()
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableExpiresAt(v *int64) *SessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// AddExpiresAt adds value to the "expires_at" field.
func (_u *SessionUpdateOne) AddExpiresAt(v int64) *SessionUpdateOne {
	_u.mutation.AddExpiresAt(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *SessionUpdateOne) SetOwnerID(id string) *SessionUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *SessionUpdateOne) SetOwner(v *User) *SessionUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *SessionUpdateOne) ClearOwner() *SessionUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SessionUpdateOne) check() error {
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Session.owner"`)
	}
	return nil
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TokenHash(); ok {
		_spec.SetField(session.FieldTokenHash, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(session.FieldCreatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedExpiresAt(); ok {
		_spec.AddField(session.FieldExpiresAt, field.TypeInt64, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.OwnerTable,
			Columns: []string{session.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
