// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/unblockrequest"
)

// UnblockRequest is the model entity for the UnblockRequest schema.
type UnblockRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// TargetHostname holds the value of the "target_hostname" field.
	TargetHostname string `json:"target_hostname,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    int64 `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UnblockRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case unblockrequest.FieldCreatedAt:
			values[i] = new(sql.NullInt64)
		case unblockrequest.FieldID, unblockrequest.FieldType, unblockrequest.FieldValue, unblockrequest.FieldTargetHostname:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UnblockRequest fields.
func (_m *UnblockRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case unblockrequest.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case unblockrequest.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case unblockrequest.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case unblockrequest.FieldTargetHostname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_hostname", values[i])
			} else if value.Valid {
				_m.TargetHostname = value.String
			}
		case unblockrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the UnblockRequest.
// This includes values selected through modifiers, order, etc.
func (_m *UnblockRequest) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UnblockRequest.
// Note that you need to call UnblockRequest.Unwrap() before calling this method if this UnblockRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UnblockRequest) Update() *UnblockRequestUpdateOne {
	return NewUnblockRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UnblockRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UnblockRequest) Unwrap() *UnblockRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UnblockRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UnblockRequest) String() string {
	var builder strings.Builder
	builder.WriteString("UnblockRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("target_hostname=")
	builder.WriteString(_m.TargetHostname)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// UnblockRequests is a parsable slice of UnblockRequest.
type UnblockRequests []*UnblockRequest
