// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/g0lab/g0efilter/internal/dashboard/store/ent/unblockrequest"
)

// UnblockRequestCreate is the builder for creating a UnblockRequest entity.
type UnblockRequestCreate struct {
	config
	mutation *UnblockRequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetType sets the "type" field.
func (_c *UnblockRequestCreate) SetType(v string) *UnblockRequestCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *UnblockRequestCreate) SetValue(v string) *UnblockRequestCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetTargetHostname sets the "target_hostname" field.
func (_c *UnblockRequestCreate) SetTargetHostname(v string) *UnblockRequestCreate {
	_c.mutation.SetTargetHostname(v)
	return _c
}

// SetNillableTargetHostname sets the "target_hostname" field if the given value is not nil.
func (_c *UnblockRequestCreate) SetNillableTargetHostname(v *string) *UnblockRequestCreate {
	if v != nil {
		_c.SetTargetHostname(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UnblockRequestCreate) SetCreatedAt(v int64) *UnblockRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *UnblockRequestCreate) SetID(v string) *UnblockRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UnblockRequestMutation object of the builder.
func (_c *UnblockRequestCreate) Mutation() *UnblockRequestMutation {
	return _c.mutation
}

// Save creates the UnblockRequest in the database.
func (_c *UnblockRequestCreate) Save(ctx context.Context) (*UnblockRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UnblockRequestCreate) SaveX(ctx context.Context) *UnblockRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnblockRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnblockRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UnblockRequestCreate) defaults() {
	if _, ok := _c.mutation.TargetHostname(); !ok {
		v := unblockrequest.DefaultTargetHostname
		_c.mutation.SetTargetHostname(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UnblockRequestCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "UnblockRequest.type"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "UnblockRequest.value"`)}
	}
	if _, ok := _c.mutation.TargetHostname(); !ok {
		return &ValidationError{Name: "target_hostname", err: errors.New(`ent: missing required field "UnblockRequest.target_hostname"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UnblockRequest.created_at"`)}
	}
	return nil
}

func (_c *UnblockRequestCreate) sqlSave(ctx context.Context) (*UnblockRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected UnblockRequest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UnblockRequestCreate) createSpec() (*UnblockRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &UnblockRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(unblockrequest.Table, sqlgraph.NewFieldSpec(unblockrequest.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(unblockrequest.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(unblockrequest.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.TargetHostname(); ok {
		_spec.SetField(unblockrequest.FieldTargetHostname, field.TypeString, value)
		_node.TargetHostname = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(unblockrequest.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UnblockRequest.Create().
//		SetType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnblockRequestUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *UnblockRequestCreate) OnConflict(opts ...sql.ConflictOption) *UnblockRequestUpsertOne {
	_c.conflict = opts
	return &UnblockRequestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UnblockRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnblockRequestCreate) OnConflictColumns(columns ...string) *UnblockRequestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnblockRequestUpsertOne{
		create: _c,
	}
}

type (
	// UnblockRequestUpsertOne is the builder for "upsert"-ing
	//  one UnblockRequest node.
	UnblockRequestUpsertOne struct {
		create *UnblockRequestCreate
	}

	// UnblockRequestUpsert is the "OnConflict" setter.
	UnblockRequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetType sets the "type" field.
func (u *UnblockRequestUpsert) SetType(v string) *UnblockRequestUpsert {
	u.Set(unblockrequest.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UnblockRequestUpsert) UpdateType() *UnblockRequestUpsert {
	u.SetExcluded(unblockrequest.FieldType)
	return u
}

// SetValue sets the "value" field.
func (u *UnblockRequestUpsert) SetValue(v string) *UnblockRequestUpsert {
	u.Set(unblockrequest.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UnblockRequestUpsert) UpdateValue() *UnblockRequestUpsert {
	u.SetExcluded(unblockrequest.FieldValue)
	return u
}

// SetTargetHostname sets the "target_hostname" field.
func (u *UnblockRequestUpsert) SetTargetHostname(v string) *UnblockRequestUpsert {
	u.Set(unblockrequest.FieldTargetHostname, v)
	return u
}

// UpdateTargetHostname sets the "target_hostname" field to the value that was provided on create.
func (u *UnblockRequestUpsert) UpdateTargetHostname() *UnblockRequestUpsert {
	u.SetExcluded(unblockrequest.FieldTargetHostname)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UnblockRequestUpsert) SetCreatedAt(v int64) *UnblockRequestUpsert {
	u.Set(unblockrequest.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UnblockRequestUpsert) UpdateCreatedAt() *UnblockRequestUpsert {
	u.SetExcluded(unblockrequest.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *UnblockRequestUpsert) AddCreatedAt(v int64) *UnblockRequestUpsert {
	u.Add(unblockrequest.FieldCreatedAt, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.UnblockRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unblockrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnblockRequestUpsertOne) UpdateNewValues() *UnblockRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(unblockrequest.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UnblockRequest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UnblockRequestUpsertOne) Ignore() *UnblockRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnblockRequestUpsertOne) DoNothing() *UnblockRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnblockRequestCreate.OnConflict
// documentation for more info.
func (u *UnblockRequestUpsertOne) Update(set func(*UnblockRequestUpsert)) *UnblockRequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnblockRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *UnblockRequestUpsertOne) SetType(v string) *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UnblockRequestUpsertOne) UpdateType() *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateType()
	})
}

// SetValue sets the "value" field.
func (u *UnblockRequestUpsertOne) SetValue(v string) *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UnblockRequestUpsertOne) UpdateValue() *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateValue()
	})
}

// SetTargetHostname sets the "target_hostname" field.
func (u *UnblockRequestUpsertOne) SetTargetHostname(v string) *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetTargetHostname(v)
	})
}

// UpdateTargetHostname sets the "target_hostname" field to the value that was provided on create.
func (u *UnblockRequestUpsertOne) UpdateTargetHostname() *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateTargetHostname()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UnblockRequestUpsertOne) SetCreatedAt(v int64) *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *UnblockRequestUpsertOne) AddCreatedAt(v int64) *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UnblockRequestUpsertOne) UpdateCreatedAt() *UnblockRequestUpsertOne {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UnblockRequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnblockRequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnblockRequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UnblockRequestUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: UnblockRequestUpsertOne.ID is not supported by MySQL driver. Use UnblockRequestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UnblockRequestUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UnblockRequestCreateBulk is the builder for creating many UnblockRequest entities in bulk.
type UnblockRequestCreateBulk struct {
	config
	err      error
	builders []*UnblockRequestCreate
	conflict []sql.ConflictOption
}

// Save creates the UnblockRequest entities in the database.
func (_c *UnblockRequestCreateBulk) Save(ctx context.Context) ([]*UnblockRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UnblockRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UnblockRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UnblockRequestCreateBulk) SaveX(ctx context.Context) []*UnblockRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UnblockRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UnblockRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UnblockRequest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UnblockRequestUpsert) {
//			SetType(v+v).
//		}).
//		Exec(ctx)
func (_c *UnblockRequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *UnblockRequestUpsertBulk {
	_c.conflict = opts
	return &UnblockRequestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UnblockRequest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UnblockRequestCreateBulk) OnConflictColumns(columns ...string) *UnblockRequestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UnblockRequestUpsertBulk{
		create: _c,
	}
}

// UnblockRequestUpsertBulk is the builder for "upsert"-ing
// a bulk of UnblockRequest nodes.
type UnblockRequestUpsertBulk struct {
	create *UnblockRequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UnblockRequest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(unblockrequest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UnblockRequestUpsertBulk) UpdateNewValues() *UnblockRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(unblockrequest.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UnblockRequest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UnblockRequestUpsertBulk) Ignore() *UnblockRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UnblockRequestUpsertBulk) DoNothing() *UnblockRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UnblockRequestCreateBulk.OnConflict
// documentation for more info.
func (u *UnblockRequestUpsertBulk) Update(set func(*UnblockRequestUpsert)) *UnblockRequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UnblockRequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetType sets the "type" field.
func (u *UnblockRequestUpsertBulk) SetType(v string) *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UnblockRequestUpsertBulk) UpdateType() *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateType()
	})
}

// SetValue sets the "value" field.
func (u *UnblockRequestUpsertBulk) SetValue(v string) *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *UnblockRequestUpsertBulk) UpdateValue() *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateValue()
	})
}

// SetTargetHostname sets the "target_hostname" field.
func (u *UnblockRequestUpsertBulk) SetTargetHostname(v string) *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetTargetHostname(v)
	})
}

// UpdateTargetHostname sets the "target_hostname" field to the value that was provided on create.
func (u *UnblockRequestUpsertBulk) UpdateTargetHostname() *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateTargetHostname()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UnblockRequestUpsertBulk) SetCreatedAt(v int64) *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *UnblockRequestUpsertBulk) AddCreatedAt(v int64) *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UnblockRequestUpsertBulk) UpdateCreatedAt() *UnblockRequestUpsertBulk {
	return u.Update(func(s *UnblockRequestUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *UnblockRequestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UnblockRequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UnblockRequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UnblockRequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
