// Code generated by ent, DO NOT EDIT.

package apikey

import (
	"entgo.io/ent/dialect/sql"
	"github.com/g0lab/g0efilter/dashboard/store/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldID, id))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyPrefix applies equality check predicate on the "key_prefix" field. It's identical to KeyPrefixEQ.
func KeyPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyPrefix, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// LastUsedAt applies equality check predicate on the "last_used_at" field. It's identical to LastUsedAtEQ.
func LastUsedAt(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldRevokedAt, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldLabel, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...[]byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...[]byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v []byte) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldKeyHash, v))
}

// KeyPrefixEQ applies the EQ predicate on the "key_prefix" field.
func KeyPrefixEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyPrefix, v))
}

// KeyPrefixNEQ applies the NEQ predicate on the "key_prefix" field.
func KeyPrefixNEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldKeyPrefix, v))
}

// KeyPrefixIn applies the In predicate on the "key_prefix" field.
func KeyPrefixIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldKeyPrefix, vs...))
}

// KeyPrefixNotIn applies the NotIn predicate on the "key_prefix" field.
func KeyPrefixNotIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldKeyPrefix, vs...))
}

// KeyPrefixGT applies the GT predicate on the "key_prefix" field.
func KeyPrefixGT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldKeyPrefix, v))
}

// KeyPrefixGTE applies the GTE predicate on the "key_prefix" field.
func KeyPrefixGTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldKeyPrefix, v))
}

// KeyPrefixLT applies the LT predicate on the "key_prefix" field.
func KeyPrefixLT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldKeyPrefix, v))
}

// KeyPrefixLTE applies the LTE predicate on the "key_prefix" field.
func KeyPrefixLTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldKeyPrefix, v))
}

// KeyPrefixContains applies the Contains predicate on the "key_prefix" field.
func KeyPrefixContains(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContains(FieldKeyPrefix, v))
}

// KeyPrefixHasPrefix applies the HasPrefix predicate on the "key_prefix" field.
func KeyPrefixHasPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasPrefix(FieldKeyPrefix, v))
}

// KeyPrefixHasSuffix applies the HasSuffix predicate on the "key_prefix" field.
func KeyPrefixHasSuffix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasSuffix(FieldKeyPrefix, v))
}

// KeyPrefixEqualFold applies the EqualFold predicate on the "key_prefix" field.
func KeyPrefixEqualFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldKeyPrefix, v))
}

// KeyPrefixContainsFold applies the ContainsFold predicate on the "key_prefix" field.
func KeyPrefixContainsFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldKeyPrefix, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// LastUsedAtEQ applies the EQ predicate on the "last_used_at" field.
func LastUsedAtEQ(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldLastUsedAt, v))
}

// LastUsedAtNEQ applies the NEQ predicate on the "last_used_at" field.
func LastUsedAtNEQ(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldLastUsedAt, v))
}

// LastUsedAtIn applies the In predicate on the "last_used_at" field.
func LastUsedAtIn(vs ...int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldLastUsedAt, vs...))
}

// LastUsedAtNotIn applies the NotIn predicate on the "last_used_at" field.
func LastUsedAtNotIn(vs ...int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldLastUsedAt, vs...))
}

// LastUsedAtGT applies the GT predicate on the "last_used_at" field.
func LastUsedAtGT(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldLastUsedAt, v))
}

// LastUsedAtGTE applies the GTE predicate on the "last_used_at" field.
func LastUsedAtGTE(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldLastUsedAt, v))
}

// LastUsedAtLT applies the LT predicate on the "last_used_at" field.
func LastUsedAtLT(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldLastUsedAt, v))
}

// LastUsedAtLTE applies the LTE predicate on the "last_used_at" field.
func LastUsedAtLTE(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldLastUsedAt, v))
}

// LastUsedAtIsNil applies the IsNil predicate on the "last_used_at" field.
func LastUsedAtIsNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldIsNull(FieldLastUsedAt))
}

// LastUsedAtNotNil applies the NotNil predicate on the "last_used_at" field.
func LastUsedAtNotNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldNotNull(FieldLastUsedAt))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v int64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKey) predicate.APIKey {
	return predicate.APIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKey) predicate.APIKey {
	return predicate.APIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKey) predicate.APIKey {
	return predicate.APIKey(sql.NotPredicates(p))
}
