#!/usr/bin/env python3
"""Wrap deploy/crds/*.yaml as templates of the g0efilter-controller chart.

Called by scripts/gen-controller.sh. The chart installs the CRDs from its own
templates so that `helm upgrade` applies schema changes, which Helm's crds/
directory never does. Generating the templates from deploy/crds keeps that
directory the single source of truth.

Every CRD is annotated helm.sh/resource-policy: keep. Deleting a CRD deletes
every policy it holds, so `helm uninstall` must not be able to do it.
"""

import sys
from pathlib import Path

GUARD_OPEN = "{{- if .Values.crds.install }}\n"
GUARD_CLOSE = "{{- end }}\n"
KEEP = "    helm.sh/resource-policy: keep\n"
HEADER = "# Generated by scripts/gen-controller.sh from deploy/crds. Do not edit.\n"


def wrap(source: Path, destination: Path) -> None:
    lines = source.read_text().splitlines(keepends=True)

    out = [HEADER, GUARD_OPEN]
    annotated = False
    for line in lines:
        # controller-gen always emits a metadata.annotations block holding its own
        # version, so the keep annotation is appended to it rather than created.
        out.append(line)
        if not annotated and line.startswith("  annotations:"):
            out.append(KEEP)
            annotated = True

    if not annotated:
        raise SystemExit(f"{source}: no metadata.annotations block to extend")

    if not out[-1].endswith("\n"):
        out.append("\n")
    out.append(GUARD_CLOSE)

    destination.write_text("".join(out))
    print(f"    {destination.relative_to(destination.parents[4])}")


def main() -> None:
    root = Path(sys.argv[1]).resolve()
    crds = sorted((root / "deploy" / "crds").glob("*.yaml"))
    if not crds:
        raise SystemExit("no CRDs in deploy/crds")

    templates = root / "deploy" / "helm" / "g0efilter-controller" / "templates"
    templates.mkdir(parents=True, exist_ok=True)

    for stale in templates.glob("crd-*.yaml"):
        stale.unlink()

    for crd in crds:
        # g0efilter.io_egresspolicies.yaml -> crd-egresspolicies.yaml
        plural = crd.stem.split("_", 1)[-1]
        wrap(crd, templates / f"crd-{plural}.yaml")


if __name__ == "__main__":
    main()
