#!/usr/bin/env bash
# Wraps deploy/crds/*.yaml as controller chart templates. The source CRDs remain
# authoritative; the templates add only a values guard and uninstall protection.
set -euo pipefail

ROOT="$(cd "${1:?repository root is required}" && pwd)"
TEMPLATES="$ROOT/deploy/helm/g0efilter-controller/templates"

shopt -s nullglob
crds=("$ROOT"/deploy/crds/*.yaml)
if ((${#crds[@]} == 0)); then
	echo "no CRDs in deploy/crds" >&2
	exit 1
fi

mkdir -p "$TEMPLATES"
stale=("$TEMPLATES"/crd-*.yaml)
if ((${#stale[@]} > 0)); then
	rm -f -- "${stale[@]}"
fi

for source in "${crds[@]}"; do
	name="${source##*/}"
	plural="${name#*_}"
	destination="$TEMPLATES/crd-${plural%.yaml}.yaml"
	temporary="$(mktemp "$TEMPLATES/.crd.XXXXXX")"

	if ! awk '
		BEGIN {
			print "# Generated by scripts/gen-controller.sh from deploy/crds. Do not edit."
			print "{{- if .Values.crds.install }}"
		}
		{
			print
			if (!annotated && $0 ~ /^  annotations:/) {
				print "    helm.sh/resource-policy: keep"
				annotated = 1
			}
		}
		END {
			if (!annotated) {
				exit 1
			}
			print "{{- end }}"
		}
	' "$source" >"$temporary"; then
		rm -f -- "$temporary"
		echo "$source: no metadata.annotations block to extend" >&2
		exit 1
	fi

	mv "$temporary" "$destination"
	echo "    ${destination#"$ROOT"/}"
done
