---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.g0efilter.policy.configMapName }}
data:
  policy.yaml: |
    allowlist:
      ips:
      {{- range .Values.policy.ips }}
        - {{ . | quote }}
      {{- end }}
      domains:
      {{- range .Values.policy.domains }}
        - {{ . | quote }}
      {{- end }}
