FROM gcr.io/distroless/static:nonroot@sha256:1c2c046bc09ed40fad370b599a0b1ae7987f55b01e247cf27a7c27cd97e5bbc7

WORKDIR /

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/g0efilter-controller /g0efilter-controller

# distroless/static:nonroot has no shell and defaults to uid 65532.
USER 65532:65532

ENTRYPOINT ["/g0efilter-controller"]
