FROM gcr.io/distroless/static:nonroot@sha256:e2e927ec666bae08560abb3c55d0659eceabb657f56b6782ab500a9fc7f555e3

WORKDIR /

ARG TARGETPLATFORM

COPY ${TARGETPLATFORM}/g0efilter-controller /g0efilter-controller

# distroless/static:nonroot has no shell and defaults to uid 65532.
USER 65532:65532

ENTRYPOINT ["/g0efilter-controller"]
