---
name: Docker Hub Descriptions

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/description.yaml'
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-description:
    environment: dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Filter egress
        uses: g0lab/g0efilter@v0
        with:
          egress-policy: block
          allowed-domains: |
            hub.docker.com

      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Update agent description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: g0lab/g0efilter
          enable-url-completion: true

      - name: Update dashboard description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: g0lab/g0efilter-dashboard
          enable-url-completion: true

      - name: Update controller description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: g0lab/g0efilter-controller
          enable-url-completion: true
